(in-package #:lispgb.tests)
(defun register-mooneye (path)
  (let ((name (intern (string-upcase (format nil "MOONEYE/~A" (pathname-name path))) :lispgb.tests)))
    (setf (gethash name *tests*)
          (lambda ()
            (multiple-value-bind (result machine) (mooneye-result path :max-frames 600)
              (is (eq :pass result)
                  (format nil "~A: ~S" result (lispgb.core:machine-cpu-registers machine))))))
    (when (member (pathname-name path) '("rapid_toggle" "reti_timing" "stat_lyc_onoff") :test #'string=)
      (register-known-failure name "RuxBoy でも不合格のタイミングテスト"))))
(let ((root (asdf:system-relative-pathname "lispgb/tests" "tests/roms/mooneye/acceptance/")))
  ;; PPU のテストは T026 で同じスイートに追加する。
  (dolist (path (append (directory (merge-pathnames "*.gb" root))
                       (directory (merge-pathnames "timer/*.gb" root))
                       (directory (merge-pathnames "interrupts/*.gb" root))))
    (register-mooneye path)))
