(in-package #:lispgb.tests)
(defun register-mooneye (path)
  (let ((name (intern (string-upcase (format nil "MOONEYE/~A" (enough-namestring path (asdf:system-relative-pathname "lispgb/tests" "tests/roms/mooneye/")))) :lispgb.tests)))
    (setf (gethash name *tests*)
          (lambda ()
            (multiple-value-bind (result machine) (mooneye-result path :max-frames 600)
              (is (eq :pass result)
                  (format nil "~A: ~S" result (lispgb.core:machine-cpu-registers machine))))))
    (when (member (pathname-name path) '("rapid_toggle" "reti_timing" "stat_lyc_onoff") :test #'string=)
      (register-known-failure name "RuxBoy でも不合格のタイミングテスト"))))
(let ((root (asdf:system-relative-pathname "lispgb/tests" "tests/roms/mooneye/acceptance/")))
  ;; acceptance の全 ROM を再帰的に列挙する。
  (dolist (path (directory (merge-pathnames "**/*.gb" root)))
    (register-mooneye path)))
(let ((root (asdf:system-relative-pathname "lispgb/tests" "tests/roms/mooneye/emulator-only/")))
  (dolist (path (directory (merge-pathnames "**/*.gb" root))) (register-mooneye path)))
