(in-package #:lispgb)

(defstruct audio
  (device 0) (buffer (make-array 4096 :element-type '(signed-byte 16) :initial-element 0))
  (deadline 0) (frequency 1))
(defun open-audio ()
  ;; SDL_AudioSpec: freq=0、format=4、channels=6、samples=8、callback=16、userdata=24。
  (let ((spec (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0))
        (audio (make-audio :frequency (sdl-get-performance-frequency) :deadline (sdl-get-performance-counter))))
    (when (minusp (sdl-init #x10))
      (format *error-output* "警告: 音声を初期化できません。無音で続けます: ~A~%" (sdl-get-error))
      (return-from open-audio audio))
    (sb-sys:with-pinned-objects (spec)
      (let ((sap (sb-sys:vector-sap spec)))
        (setf (sb-sys:sap-ref-32 sap 0) 48000 (sb-sys:sap-ref-16 sap 4) #x8010
              (sb-sys:sap-ref-8 sap 6) 2 (sb-sys:sap-ref-16 sap 8) 1024)
        (setf (audio-device audio) (sdl-open-audio-device (null-pointer) 0 sap (null-pointer) 0))))
    (if (zerop (audio-device audio))
        (format *error-output* "警告: 音声デバイスを開けません。無音で続けます: ~A~%" (sdl-get-error))
        (sdl-pause-audio-device (audio-device audio) 0))
    audio))
(defun close-audio (audio)
  (unless (zerop (audio-device audio)) (sdl-close-audio-device (audio-device audio))))
(defun clear-audio (audio)
  (unless (zerop (audio-device audio)) (sdl-clear-queued-audio (audio-device audio))))
(defun output-audio (audio machine &optional (volume 100))
  (let* ((buffer (audio-buffer audio)) (count (lispgb.core:drain-audio machine buffer)) (device (audio-device audio)))
    (unless (= volume 100)
      (dotimes (i count) (setf (aref buffer i) (truncate (* volume (aref buffer i)) 100))))
    (when (and (plusp device) (plusp count))
      (sb-sys:with-pinned-objects (buffer)
        (check-sdl (sdl-queue-audio device (sb-sys:vector-sap buffer) (* 2 count)))))))
(defun pace-frame (audio)
  (if (plusp (audio-device audio))
      (loop while (> (sdl-get-queued-audio-size (audio-device audio)) (ceiling (* 4 4 48000 70224) 4194304))
            do (sdl-delay 1))
      (let* ((frequency (audio-frequency audio))
             (deadline (incf (audio-deadline audio) (round (* frequency 70224) 4194304))))
        (loop while (< (sdl-get-performance-counter) deadline) do (sdl-delay 1))
        ;; 長い中断の後に大量のフレームを一気に実行しない。
        (when (> (- (sdl-get-performance-counter) deadline) (floor frequency 4))
          (setf (audio-deadline audio) (sdl-get-performance-counter))))))
