(in-package #:lispgb)
(defun write-bmp (path argb-pixels width height)
  (unless (and (typep width '(integer 1)) (typep height '(integer 1)) (= (* width height) (length argb-pixels)))
    (error "BMP の画像サイズが不正です。"))
  (let* ((stride (* 4 (ceiling (* width 3) 4))) (size (+ 54 (* stride height)))
         (bytes (make-array size :element-type '(unsigned-byte 8) :initial-element 0)))
    (flet ((put (offset value width)
             (dotimes (i width) (setf (aref bytes (+ offset i)) (ldb (byte 8 (* i 8)) value)))))
      (put 0 #x4d42 2) (put 2 size 4) (put 10 54 4) (put 14 40 4)
      (put 18 width 4) (put 22 height 4) (put 26 1 2) (put 28 24 2) (put 34 (* stride height) 4)
      (dotimes (y height)
        (dotimes (x width)
          (put (+ 54 (* y stride) (* x 3)) (aref argb-pixels (+ (* (- height 1 y) width) x)) 3))))
    (write-file-atomically path bytes)))
