(in-package #:lispgb)
(define-condition usage-error (error)
  ((message :initarg :message :reader usage-message))
  (:report (lambda (condition stream) (write-string (usage-message condition) stream))))
(defstruct cli-options rom headless frames screenshot)
(defun parse-args (arguments)
  (let ((options (make-cli-options)))
    (labels ((value () (or (pop arguments) (error 'usage-error :message "オプションの値が必要です。"))))
      (loop while arguments for argument = (pop arguments) do
        (cond ((string= argument "--headless") (setf (cli-options-headless options) t))
              ((string= argument "--frames")
               (let ((n (ignore-errors (parse-integer (value)))))
                 (unless (and n (plusp n)) (error 'usage-error :message "フレーム数は正の整数で指定してください。"))
                 (setf (cli-options-frames options) n)))
              ((string= argument "--screenshot") (setf (cli-options-screenshot options) (value)))
              ((and (plusp (length argument)) (char= #\- (char argument 0)))
               (error 'usage-error :message (format nil "不明なオプション: ~A" argument)))
              ((cli-options-rom options) (error 'usage-error :message "ROM は1つだけ指定してください。"))
              (t (setf (cli-options-rom options) argument)))))
    (unless (cli-options-rom options) (error 'usage-error :message "ROM ファイルを指定してください。"))
    (when (and (cli-options-headless options) (not (cli-options-frames options)))
      (error 'usage-error :message "--headless には --frames が必要です。"))
    (when (and (not (cli-options-headless options)) (or (cli-options-frames options) (cli-options-screenshot options)))
      (error 'usage-error :message "--frames と --screenshot は --headless と組み合わせてください。"))
    options))
(defun print-help (&optional (stream *standard-output*))
  (format stream "使い方: lispgb [--headless --frames N [--screenshot PATH]] <ROMファイル>~%"))
