(in-package #:lispgb)
(defstruct app-config (scale 4) (fullscreen nil) (shader :nearest) (volume 100))
(defparameter +default-config-text+
  (format nil "# LispGB 設定ファイル~%scale = 4~%fullscreen = false~%shader = nearest~%volume = 100~%"))
(defun trim-config (text) (string-trim '(#\Space #\Tab #\Return #\Newline) text))
(defun parse-config-text (text)
  (let ((config (make-app-config)))
    (with-input-from-string (stream text)
      (loop for line = (read-line stream nil) while line do
        (let* ((line (subseq line 0 (position #\# line))) (separator (position #\= line)))
          (when separator
            (let* ((key (trim-config (subseq line 0 separator))) (value (trim-config (subseq line (1+ separator))))
                   (number (ignore-errors (parse-integer value))))
              (cond ((and (string= key "scale") number (plusp number)) (setf (app-config-scale config) (min 8 number)))
                    ((string= key "fullscreen")
                     (cond ((string= value "true") (setf (app-config-fullscreen config) t))
                           ((string= value "false") (setf (app-config-fullscreen config) nil))))
                    ((string= key "shader")
                     (cond ((string= value "nearest") (setf (app-config-shader config) :nearest))
                           ((string= value "smooth") (setf (app-config-shader config) :smooth))))
                    ((and (string= key "volume") number (<= 0 number 100)) (setf (app-config-volume config) number))))))))
    config))
(defun load-config (&optional (directory (config-directory)))
  (handler-case
      (let ((path (merge-pathnames "config.txt" directory)))
        (unless (probe-file path)
          (ensure-directories-exist path)
          (write-file-atomically path (sb-ext:string-to-octets +default-config-text+ :external-format :utf-8)))
        (values (parse-config-text (uiop:read-file-string path :external-format :utf-8)) directory))
    (error (condition)
      (format *error-output* "警告: 設定を読み書きできません。既定値で続けます: ~A~%" condition)
      (values (make-app-config) nil))))
(defun apply-cli-config (config options)
  (let ((result (copy-app-config config)))
    (when (cli-options-scale options) (setf (app-config-scale result) (cli-options-scale options)))
    (when (cli-options-fullscreen options) (setf (app-config-fullscreen result) t))
    (when (cli-options-shader options) (setf (app-config-shader result) (cli-options-shader options)))
    result))
