(in-package #:lispgb)

(defparameter +version+ #.(asdf:component-version (asdf:find-system "lispgb")))

(defun sync-rtc (machine)
  (lispgb.core::mbc-sync-wall-clock (lispgb.core::bus-cart (lispgb.core::machine-bus machine))
                                  (- (get-universal-time) 2208988800)))
(defstruct persistence path (quiet-frames 0) (pending nil))
(defun machine-cartridge (machine) (lispgb.core::bus-cart (lispgb.core::machine-bus machine)))
(defun open-persistence (machine rom-path)
  (let* ((cart (machine-cartridge machine)) (ram (lispgb.core::cartridge-ram cart)))
    (when (and (lispgb.core::cartridge-header-battery-p (lispgb.core::cartridge-header cart)) (plusp (length ram)))
      (let ((path (save-ram-path rom-path)))
        (when (probe-file path)
          (let ((saved (read-file-octets path)))
            (if (= (length saved) (length ram)) (replace ram saved)
                (let* ((base (concatenate 'string (namestring path) ".bak"))
                       (backup (loop for i from 0 for candidate = (if (zerop i) base (format nil "~A.~D" base i))
                                     unless (probe-file candidate) return candidate)))
                  (rename-file path (merge-pathnames backup (uiop:getcwd)))
                  (format *error-output* "警告: セーブ RAM のサイズが違うため、~A に退避しました。~%" backup)))))
        (make-persistence :path path)))))
(defun flush-save-ram (persistence machine)
  (when persistence
    (write-file-atomically (persistence-path persistence) (lispgb.core::cartridge-ram (machine-cartridge machine)))
    (setf (persistence-pending persistence) nil (persistence-quiet-frames persistence) 0
          (lispgb.core::cartridge-ram-dirty (machine-cartridge machine)) nil)))
(defun update-save-ram (persistence machine)
  (when persistence
    (let ((cart (machine-cartridge machine)))
      (cond ((lispgb.core::cartridge-ram-dirty cart)
             (setf (lispgb.core::cartridge-ram-dirty cart) nil (persistence-pending persistence) t
                   (persistence-quiet-frames persistence) 0))
            ((and (persistence-pending persistence) (>= (incf (persistence-quiet-frames persistence)) 60))
             (flush-save-ram persistence machine))))))
(defun handle-state-event (event machine rom-path audio)
  (handler-case
      (case event
        (:save (write-file-atomically (state-path rom-path) (lispgb.core:save-state machine)))
        (:load (lispgb.core:load-state machine (read-file-octets (state-path rom-path)))
               (clear-audio audio)))
    (error (condition) (format *error-output* "保存・復元エラー: ~A~%" condition))))
(defun play-machine (machine &key persistence rom-path (config (make-app-config)))
  (load-sdl2)
  (unwind-protect
      (progn
        (check-sdl (sdl-init #x21))
        (let ((video (open-video :scale (app-config-scale config) :fullscreen (app-config-fullscreen config) :shader (app-config-shader config))))
          (unwind-protect
              (let ((audio (open-audio)) (input (make-input)))
                (unwind-protect
                    (loop
                      (let ((events (poll-input input)))
                        (when (member :quit events) (return))
                        (when rom-path
                          (dolist (event events) (handle-state-event event machine rom-path audio))))
                      (lispgb.core:set-buttons machine (input-buttons input))
                      (sync-rtc machine)
                      (lispgb.core:run-frame machine)
                      (update-save-ram persistence machine)
                      (present-frame video (lispgb.core:machine-framebuffer machine))
                      (output-audio audio machine (app-config-volume config))
                      (pace-frame audio))
                  (close-audio audio)))
            (close-video video))))
    (sdl-quit)))
(defun run-headless (machine options persistence)
  (dotimes (i (cli-options-frames options))
    (sync-rtc machine)
    (lispgb.core:run-frame machine)
    (update-save-ram persistence machine))
  (when (cli-options-screenshot options)
    (write-bmp (cli-options-screenshot options) (lispgb.core:machine-framebuffer machine) 160 144)))
(defun execute-options (options &key directory (config (make-app-config)))
  (let* ((rom-path (cli-options-rom options))
         (machine (lispgb.core:make-machine (read-file-octets rom-path)))
         (persistence (open-persistence machine rom-path)))
    (remember-rom directory rom-path)
    (unwind-protect
        (if (cli-options-headless options) (run-headless machine options persistence)
            (play-machine machine :persistence persistence :rom-path rom-path :config config))
      (flush-save-ram persistence machine))))
(defun main ()
  (uiop:quit
   (handler-case
       (let ((options (parse-args (uiop:command-line-arguments))))
         (cond ((cli-options-help options) (print-help))
               ((cli-options-version options) (format t "LispGB ~A~%" +version+))
               (t (multiple-value-bind (config directory) (load-config)
                    (if (cli-options-recent options)
                        (dolist (path (read-recent directory)) (format t "~A~%" path))
                        (execute-options options :directory directory :config (apply-cli-config config options))))))
         0)
     (usage-error (condition) (format *error-output* "~A~%" condition) (print-help *error-output*) 2)
     (error (condition) (format *error-output* "実行エラー: ~A~%" condition) 1))))
