(in-package #:lispgb)

(defun sync-rtc (machine)
  (lispgb.core::mbc-sync-wall-clock (lispgb.core::bus-cart (lispgb.core::machine-bus machine))
                                  (- (get-universal-time) 2208988800)))
(defstruct persistence path (quiet-frames 0) (pending nil))
(defun machine-cartridge (machine) (lispgb.core::bus-cart (lispgb.core::machine-bus machine)))
(defun open-persistence (machine rom-path)
  (let* ((cart (machine-cartridge machine)) (ram (lispgb.core::cartridge-ram cart)))
    (when (and (lispgb.core::cartridge-header-battery-p (lispgb.core::cartridge-header cart)) (plusp (length ram)))
      (let ((path (save-ram-path rom-path)))
        (when (probe-file path)
          (let ((saved (read-file-octets path)))
            (if (= (length saved) (length ram)) (replace ram saved)
                (let* ((base (concatenate 'string (namestring path) ".bak"))
                       (backup (loop for i from 0 for candidate = (if (zerop i) base (format nil "~A.~D" base i))
                                     unless (probe-file candidate) return candidate)))
                  (rename-file path backup)
                  (format *error-output* "警告: セーブ RAM のサイズが違うため、~A に退避しました。~%" backup)))))
        (make-persistence :path path)))))
(defun flush-save-ram (persistence machine)
  (when persistence
    (write-file-atomically (persistence-path persistence) (lispgb.core::cartridge-ram (machine-cartridge machine)))
    (setf (persistence-pending persistence) nil (persistence-quiet-frames persistence) 0
          (lispgb.core::cartridge-ram-dirty (machine-cartridge machine)) nil)))
(defun update-save-ram (persistence machine)
  (when persistence
    (let ((cart (machine-cartridge machine)))
      (cond ((lispgb.core::cartridge-ram-dirty cart)
             (setf (lispgb.core::cartridge-ram-dirty cart) nil (persistence-pending persistence) t
                   (persistence-quiet-frames persistence) 0))
            ((and (persistence-pending persistence) (>= (incf (persistence-quiet-frames persistence)) 60))
             (flush-save-ram persistence machine))))))
(defun play-machine (machine &key persistence)
  (load-sdl2)
  (unwind-protect
      (progn
        (check-sdl (sdl-init #x21))
        (let ((video (open-video)))
          (unwind-protect
              (let ((audio (open-audio)) (input (make-input)))
                (unwind-protect
                    (loop
                      (when (member :quit (poll-input input)) (return))
                      (lispgb.core:set-buttons machine (input-buttons input))
                      (sync-rtc machine)
                      (lispgb.core:run-frame machine)
                      (update-save-ram persistence machine)
                      (present-frame video (lispgb.core:machine-framebuffer machine))
                      (output-audio audio machine)
                      (pace-frame audio))
                  (close-audio audio)))
            (close-video video))))
    (sdl-quit)))
(defun main ()
  (let ((args (uiop:command-line-arguments)))
    (unless (and (= 1 (length args)) (not (and (plusp (length (first args))) (char= #\- (char (first args) 0)))))
      (format *error-output* "使い方: lispgb <ROMファイル>~%")
      (uiop:quit 2))
    (handler-case
        (let* ((machine (lispgb.core:make-machine (read-file-octets (first args))))
               (persistence (open-persistence machine (first args))))
          (unwind-protect (play-machine machine :persistence persistence)
            (flush-save-ram persistence machine))
          (uiop:quit 0))
      (error (condition) (format *error-output* "実行エラー: ~A~%" condition) (uiop:quit 1)))))
