(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct audio-channel
  (enabled nil :type boolean) (dac nil :type boolean)
  (length 0 :type fixnum) (length-enabled nil :type boolean)
  (frequency 0 :type fixnum) (timer 0 :type fixnum) (position 0 :type fixnum)
  (volume 0 :type fixnum) (envelope-timer 0 :type fixnum)
  (lfsr #x7fff :type u16) (area 0 :type fixnum))
(defstruct apu
  (enabled nil :type boolean)
  (wave-access 0 :type fixnum) (wave-sample 0 :type u8)
  (registers (make-array 48 :element-type 'u8 :initial-element 0) :type octets)
  (channels (vector (make-audio-channel) (make-audio-channel) (make-audio-channel) (make-audio-channel)) :type simple-vector)
  (frame-step 0 :type fixnum) (frame-cycles 0 :type fixnum)
  (sweep-shadow 0 :type fixnum) (sweep-timer 0 :type fixnum)
  (sweep-enabled nil :type boolean) (sweep-negated nil :type boolean)
  (sample-accumulator 0 :type fixnum) (sample-cycles 0 :type fixnum)
  (ring (make-array 16384 :element-type '(signed-byte 16) :initial-element 0) :type (simple-array (signed-byte 16) (*)))
  (ring-read 0 :type fixnum) (ring-write 0 :type fixnum) (ring-count 0 :type fixnum))
(declaim (inline apu-reg))
(defun apu-reg (apu address) (aref (apu-registers apu) (- address #xff10)))
(defun (setf apu-reg) (value apu address) (setf (aref (apu-registers apu) (- address #xff10)) value))
(defun apu-wave-address (apu address)
  "発音中の波形 RAM はフェッチ直後の 2 T サイクルだけ現在位置を参照する。"
  (let ((ch (aref (apu-channels apu) 2)))
    (if (audio-channel-enabled ch)
        (when (plusp (apu-wave-access apu))
          (+ #xff30 (ash (audio-channel-position ch) -1)))
        address)))
(defun apu-read (apu address)
  (cond
    ((= address #xff26)
     (logior #x70 (if (apu-enabled apu) #x80 0)
             (loop for ch across (apu-channels apu) for i from 0
                   when (and (apu-enabled apu) (audio-channel-enabled ch)) sum (ash 1 i))))
    ((<= #xff30 address #xff3f)
     (let ((mapped (apu-wave-address apu address))) (if mapped (apu-reg apu mapped) #xff)))
    ((<= #xff10 address #xff25)
     (logior (apu-reg apu address)
             (aref #(#x80 #x3f 0 #xff #xbf #xff #x3f 0 #xff #xbf #x7f #xff #x9f #xff #xbf #xff #xff 0 0 #xbf 0 0)
                   (- address #xff10))))
    (t #xff)))
(defun apu-period (apu index ch)
  (case index
    ((0 1) (* 4 (- 2048 (audio-channel-frequency ch))))
    (2 (* 2 (- 2048 (audio-channel-frequency ch))))
    (3 (let* ((reg (apu-reg apu #xff22)) (divisor (logand reg 7)))
         (ash (if (zerop divisor) 8 (* 16 divisor)) (ash reg -4))))))
(defun apu-sweep-calculate (apu)
  (let* ((reg (apu-reg apu #xff10)) (shadow (apu-sweep-shadow apu)) (delta (ash shadow (- (logand 7 reg)))))
    (if (logbitp 3 reg) (progn (setf (apu-sweep-negated apu) t) (- shadow delta)) (+ shadow delta))))
(defun apu-sweep-clock (apu)
  (let ((ch (aref (apu-channels apu) 0)))
    (when (and (audio-channel-enabled ch) (apu-sweep-enabled apu))
      (when (<= (decf (apu-sweep-timer apu)) 0)
        (let* ((reg (apu-reg apu #xff10)) (period (ldb (byte 3 4) reg))
               (next (if (plusp period) (apu-sweep-calculate apu) (apu-sweep-shadow apu))))
          (setf (apu-sweep-timer apu) (if (zerop period) 8 period))
          (cond ((> next 2047) (setf (audio-channel-enabled ch) nil))
                ((and (plusp period) (plusp (logand reg 7)))
                 (setf (apu-sweep-shadow apu) next (audio-channel-frequency ch) next
                       (audio-channel-timer ch) (* 4 (- 2048 next)))
                 (when (> (apu-sweep-calculate apu) 2047) (setf (audio-channel-enabled ch) nil)))))))))
(defun apu-frame-clock (apu)
  (let ((step (apu-frame-step apu)))
    (when (evenp step)
      (loop for ch across (apu-channels apu) do
        (when (and (audio-channel-length-enabled ch) (plusp (audio-channel-length ch)))
          (when (zerop (decf (audio-channel-length ch))) (setf (audio-channel-enabled ch) nil)))))
    (when (member step '(2 6)) (apu-sweep-clock apu))
    (when (= step 7)
      (loop for index in '(0 1 3) for address in '(#xff12 #xff17 #xff21)
            for ch = (aref (apu-channels apu) index) for reg = (apu-reg apu address)
            for period = (logand reg 7)
            when (and (plusp period) (<= (decf (audio-channel-envelope-timer ch)) 0)) do
              (setf (audio-channel-envelope-timer ch) period)
              (let ((volume (+ (audio-channel-volume ch) (if (logbitp 3 reg) 1 -1))))
                (when (<= 0 volume 15) (setf (audio-channel-volume ch) volume)))))
    (setf (apu-frame-step apu) (logand 7 (1+ step)))))
(defun apu-div-write (apu old-divider)
  (when (apu-enabled apu)
    (when (logbitp 12 old-divider) (apu-frame-clock apu))
    (setf (apu-frame-cycles apu) 0)))
(defun apu-trigger (apu index value)
  (let* ((ch (aref (apu-channels apu) index)) (trigger (logbitp 7 value))
         (lengthp (logbitp 6 value)) (extra (oddp (apu-frame-step apu))))
    (when (and extra lengthp (not (audio-channel-length-enabled ch)) (plusp (audio-channel-length ch)))
      (when (and (zerop (decf (audio-channel-length ch))) (not trigger)) (setf (audio-channel-enabled ch) nil)))
    (setf (audio-channel-length-enabled ch) lengthp)
    (when trigger
      (when (= index 2)
        (when (and (audio-channel-enabled ch) (= (audio-channel-timer ch) 2))
          (let ((offset (logand 15 (ash (1+ (audio-channel-position ch)) -1))))
            (if (< offset 4)
                (setf (apu-reg apu #xff30) (apu-reg apu (+ #xff30 offset)))
                (dotimes (i 4)
                  (setf (apu-reg apu (+ #xff30 i))
                        (apu-reg apu (+ #xff30 (logand offset #xfc) i)))))))
        (setf (apu-wave-access apu) 0))
      (when (zerop (audio-channel-length ch))
        (setf (audio-channel-length ch) (- (if (= index 2) 256 64) (if (and extra lengthp) 1 0))))
      (setf (audio-channel-enabled ch) (audio-channel-dac ch)
            (audio-channel-position ch) 0 (audio-channel-timer ch) (+ (apu-period apu index ch) (if (= index 2) 6 0))
            (audio-channel-lfsr ch) #x7fff)
      (unless (= index 2)
        (let ((reg (apu-reg apu (aref #(#xff12 #xff17 0 #xff21) index))))
          (setf (audio-channel-volume ch) (ash reg -4) (audio-channel-envelope-timer ch) (logand reg 7))))
      (when (= index 0)
        (let* ((reg (apu-reg apu #xff10)) (period (ldb (byte 3 4) reg)))
          (setf (apu-sweep-shadow apu) (audio-channel-frequency ch)
                (apu-sweep-timer apu) (if (zerop period) 8 period)
                (apu-sweep-enabled apu) (not (zerop (logand reg #x77))) (apu-sweep-negated apu) nil)
          (when (and (plusp (logand reg 7)) (> (apu-sweep-calculate apu) 2047))
            (setf (audio-channel-enabled ch) nil)))))))
(defun apu-write (apu address value)
  (cond
    ((= address #xff26)
     (let ((enabled (logbitp 7 value)))
       (when (and (apu-enabled apu) (not enabled))
         (fill (apu-registers apu) 0 :end #x17)
         (dotimes (i 4)
           (let ((old (aref (apu-channels apu) i)))
             (setf (aref (apu-channels apu) i)
                   (make-audio-channel :length (audio-channel-length old)))))
         (setf (apu-sweep-enabled apu) nil (apu-sweep-negated apu) nil))
       (unless (eq enabled (apu-enabled apu)) (setf (apu-frame-step apu) 0 (apu-frame-cycles apu) 0))
       (setf (apu-enabled apu) enabled)))
    ((<= #xff30 address #xff3f)
     (let ((mapped (apu-wave-address apu address))) (when mapped (setf (apu-reg apu mapped) value))))
    ((and (<= #xff10 address #xff25) (or (apu-enabled apu) (member address '(#xff11 #xff16 #xff1b #xff20))))
     (let* ((index (cond ((< address #xff16) 0) ((< address #xff1a) 1) ((< address #xff20) 2) (t 3)))
            (ch (aref (apu-channels apu) index)) (old (apu-reg apu address)))
       (unless (member address '(#xff15 #xff1f))
         (setf (apu-reg apu address) (if (apu-enabled apu) value 0)))
       (case address
         (#xff10 (when (and (logbitp 3 old) (not (logbitp 3 value)) (apu-sweep-negated apu))
                    (setf (audio-channel-enabled ch) nil)))
         ((#xff11 #xff16 #xff20) (setf (audio-channel-length ch) (- 64 (logand value 63))))
         (#xff1b (setf (audio-channel-length ch) (- 256 value)))
         ((#xff12 #xff17 #xff21 #xff1a)
          (setf (audio-channel-dac ch) (if (= index 2) (logbitp 7 value) (not (zerop (logand #xf8 value)))))
          (unless (audio-channel-dac ch) (setf (audio-channel-enabled ch) nil)))
         ((#xff13 #xff18 #xff1d)
          (setf (audio-channel-frequency ch) (logior (logand #x700 (audio-channel-frequency ch)) value)))
         ((#xff14 #xff19 #xff1e #xff23)
          (unless (= index 3)
            (setf (audio-channel-frequency ch) (logior (logand #xff (audio-channel-frequency ch)) (ash (logand 7 value) 8))))
          (setf (apu-reg apu address) (logand #x7f value))
          (apu-trigger apu index value)))))))

(defun apu-channel-units (apu index ch)
  (if (not (and (audio-channel-enabled ch) (audio-channel-dac ch))) 0
      (case index
        ((0 1) (let ((duty (ash (apu-reg apu (if (zerop index) #xff11 #xff16)) -6)))
                 (* (audio-channel-volume ch)
                    (if (logbitp (audio-channel-position ch) (aref #(#x80 #x81 #xe1 #x7e) duty)) 1 -1))))
        (2 (let* ((level (ldb (byte 2 5) (apu-reg apu #xff1c))) (position (audio-channel-position ch))
                  (sample (apu-wave-sample apu)))
             (if (zerop level) 0
                 (- (* 2 (ash (ldb (byte 4 (if (evenp position) 4 0)) sample) (- 1 level))) 15))))
        (3 (* (audio-channel-volume ch) (if (logbitp 0 (audio-channel-lfsr ch)) -1 1))))))
(defun apu-wave-step (apu index ch)
  (incf (audio-channel-timer ch) (apu-period apu index ch))
  (if (= index 3)
      (let ((feedback (logand 1 (logxor (audio-channel-lfsr ch) (ash (audio-channel-lfsr ch) -1)))))
        (setf (audio-channel-lfsr ch) (dpb feedback (byte 1 14) (ash (audio-channel-lfsr ch) -1)))
        (when (logbitp 3 (apu-reg apu #xff22))
          (setf (audio-channel-lfsr ch) (dpb feedback (byte 1 6) (audio-channel-lfsr ch)))))
      (setf (audio-channel-position ch) (logand (if (= index 2) 31 7) (1+ (audio-channel-position ch)))))
  (when (= index 2)
    (setf (apu-wave-access apu) 2
          (apu-wave-sample apu) (apu-reg apu (+ #xff30 (ash (audio-channel-position ch) -1))))))
(defun apu-emit-sample (apu)
  (let ((left 0) (right 0) (pan (apu-reg apu #xff25)) (volume (apu-reg apu #xff24)))
    (dotimes (i 4)
      (let* ((ch (aref (apu-channels apu) i))
             (units (if (and (apu-enabled apu) (plusp (apu-sample-cycles apu)))
                        (truncate (audio-channel-area ch) (apu-sample-cycles apu)) 0)))
        (when (logbitp i pan) (incf right units))
        (when (logbitp (+ 4 i) pan) (incf left units))
        (setf (audio-channel-area ch) 0)))
    (let ((offset (* 2 (apu-ring-write apu))))
      (setf (aref (apu-ring apu) offset) (truncate (* left (1+ (ldb (byte 3 4) volume)) 32767) 480)
            (aref (apu-ring apu) (1+ offset)) (truncate (* right (1+ (logand volume 7)) 32767) 480)))
    (setf (apu-ring-write apu) (logand 8191 (1+ (apu-ring-write apu))) (apu-sample-cycles apu) 0)
    (if (< (apu-ring-count apu) 8192) (incf (apu-ring-count apu))
        (setf (apu-ring-read apu) (logand 8191 (1+ (apu-ring-read apu)))))))
(defun apu-tick (apu cycles)
  "次の波形・フレーム・サンプル境界まで積分してから状態を更新する。"
  (loop while (plusp cycles) do
    (let ((span (min cycles (ceiling (- 4194304 (apu-sample-accumulator apu)) 48000))))
      (when (apu-enabled apu)
        (setf span (min span (- 8192 (apu-frame-cycles apu))))
        (loop for ch across (apu-channels apu) when (audio-channel-enabled ch)
              do (setf span (min span (max 1 (audio-channel-timer ch))))))
      (setf (apu-wave-access apu) (max 0 (- (apu-wave-access apu) span)))
      (when (apu-enabled apu)
        (dotimes (i 4)
          (let ((ch (aref (apu-channels apu) i)))
            (incf (audio-channel-area ch) (* span (apu-channel-units apu i ch)))
            (when (audio-channel-enabled ch)
              (decf (audio-channel-timer ch) span)
              (when (<= (audio-channel-timer ch) 0) (apu-wave-step apu i ch)))))
        (when (= 8192 (incf (apu-frame-cycles apu) span))
          (setf (apu-frame-cycles apu) 0) (apu-frame-clock apu)))
      (incf (apu-sample-cycles apu) span)
      (when (>= (incf (apu-sample-accumulator apu) (* span 48000)) 4194304)
        (decf (apu-sample-accumulator apu) 4194304) (apu-emit-sample apu))
      (decf cycles span))))
(defun apu-drain (apu dst)
  (let ((count (min (apu-ring-count apu) (floor (length dst) 2))))
    (dotimes (i count)
      (let ((offset (* 2 (apu-ring-read apu))))
        (setf (aref dst (* i 2)) (aref (apu-ring apu) offset)
              (aref dst (1+ (* i 2))) (aref (apu-ring apu) (1+ offset))))
      (setf (apu-ring-read apu) (logand 8191 (1+ (apu-ring-read apu)))))
    (decf (apu-ring-count apu) count) (* count 2)))
