(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defun zero-octets (size) (make-array size :element-type 'u8 :initial-element 0))
(defstruct bus
  (mode :dmg :type symbol) (cart nil :type (or null cartridge))
  (rom (zero-octets 32768) :type octets) (ram (zero-octets 8192) :type octets)
  (wram (zero-octets 32768) :type octets) (vram (zero-octets 16384) :type octets)
  (oam (zero-octets 160) :type octets) (hram (zero-octets 127) :type octets)
  (io (zero-octets 128) :type octets) (ie 0 :type u8) (if 0 :type u8)
  (svbk 1 :type u8) (vbk 0 :type u8)
  (hdma-source 0 :type u16) (hdma-destination #x8000 :type u16)
  (hdma-remaining 0 :type fixnum) (hdma-active nil :type boolean) (hdma-stall 0 :type fixnum)
  (dma-active nil :type boolean) (dma-source 0 :type u16)
  (dma-index 0 :type fixnum) (dma-delay 0 :type fixnum) (dma-clock 0 :type fixnum)
  (cycles 0 :type fixnum) (hw-cycles 0 :type fixnum)
  (double-speed nil :type boolean) (speed-switch-prepared nil :type boolean)
  (timer (make-timer) :type timer) (ppu (make-ppu) :type ppu) (apu (make-apu) :type apu) (joypad (make-joypad) :type joypad)
  (serial-log (make-array 0 :element-type 'u8 :adjustable t :fill-pointer 0)))

(defun bus-hdma-block (bus)
  (dotimes (i 16)
    (setf (aref (bus-vram bus) (+ (* 8192 (bus-vbk bus)) (logand #x1fff (+ (bus-hdma-destination bus) i))))
          (bus-read bus (wrap16 (+ (bus-hdma-source bus) i)))))
  (setf (bus-hdma-source bus) (wrap16 (+ 16 (bus-hdma-source bus)))
        (bus-hdma-destination bus) (logior #x8000 (logand #x1ff0 (+ 16 (bus-hdma-destination bus)))))
  (decf (bus-hdma-remaining bus))
  (when (zerop (bus-hdma-remaining bus)) (setf (bus-hdma-active bus) nil))
  (incf (bus-hdma-stall bus) (if (bus-double-speed bus) 64 32)))
(defun bus-hdma-start (bus value)
  (cond ((and (bus-hdma-active bus) (not (logbitp 7 value))) (setf (bus-hdma-active bus) nil))
        ((not (bus-hdma-active bus))
         (setf (bus-hdma-remaining bus) (1+ (logand value #x7f))
               (bus-hdma-active bus) (logbitp 7 value))
         (unless (bus-hdma-active bus)
           (loop while (plusp (bus-hdma-remaining bus)) do (bus-hdma-block bus))
           (bus-tick bus 0)))))
(defun bus-cgb-read (bus address)
  (if (not (eq (bus-mode bus) :cgb)) #xff
      (case address
        (#xff4d (logior #x7e (if (bus-double-speed bus) #x80 0) (if (bus-speed-switch-prepared bus) 1 0)))
        (#xff55 (if (zerop (bus-hdma-remaining bus)) #xff
                    (logior (if (bus-hdma-active bus) 0 #x80) (1- (bus-hdma-remaining bus)))))
        ((#xff68 #xff69 #xff6a #xff6b #xff6c) (ppu-read (bus-ppu bus) address))
        (otherwise #xff))))
(defun bus-cgb-write (bus address value)
  (when (eq (bus-mode bus) :cgb)
    (case address
      (#xff4d (setf (bus-speed-switch-prepared bus) (logbitp 0 value)))
      (#xff51 (setf (bus-hdma-source bus) (logior (ash value 8) (logand #xf0 (bus-hdma-source bus)))))
      (#xff52 (setf (bus-hdma-source bus) (logior (logand #xff00 (bus-hdma-source bus)) (logand #xf0 value))))
      (#xff53 (setf (bus-hdma-destination bus) (logior #x8000 (ash (logand #x1f value) 8) (logand #xf0 (bus-hdma-destination bus)))))
      (#xff54 (setf (bus-hdma-destination bus) (logior #x8000 (logand #x1f00 (bus-hdma-destination bus)) (logand #xf0 value))))
      (#xff55 (bus-hdma-start bus value))
      ((#xff68 #xff69 #xff6a #xff6b #xff6c) (ppu-write (bus-ppu bus) address value)))))
(defun bus-device-read (bus address)
  (cond ((= address #xff00) (joypad-read (bus-joypad bus)))
        ((<= #xff10 address #xff3f) (apu-read (bus-apu bus) address))
        ((<= #xff04 address #xff07) (timer-read (bus-timer bus) address))
        ((and (<= #xff40 address #xff4b) (/= address #xff46)) (ppu-read (bus-ppu bus) address))
        (t (aref (bus-io bus) (- address #xff00)))))
(defun bus-device-write (bus address value)
  (cond ((= address #xff00)
         (when (joypad-update (bus-joypad bus) :selection value) (setf (bus-if bus) (logior #x10 (bus-if bus)))))
        ((<= #xff10 address #xff3f) (apu-write (bus-apu bus) address value))
        ((<= #xff04 address #xff07)
         (when (= address #xff04) (apu-div-write (bus-apu bus) (ash (timer-div-counter (bus-timer bus)) (if (bus-double-speed bus) -1 0))))
         (timer-write (bus-timer bus) address value))
        ((and (<= #xff40 address #xff4b) (/= address #xff46))
         (when (ppu-write (bus-ppu bus) address value) (setf (bus-if bus) (logior 2 (bus-if bus)))))
        ((= address #xff46)
         (setf (bus-dma-source bus) (ash value 8) (bus-dma-delay bus) 2 (bus-dma-clock bus) 0))
        (t (setf (aref (bus-io bus) (- address #xff00)) value))))
(defun bus-tick (bus cycles)
  (declare (type bus bus) (type fixnum cycles))
  (apu-tick (bus-apu bus) (if (bus-double-speed bus) (ash cycles -1) cycles))
  (when (timer-tick (bus-timer bus) cycles)
    (setf (bus-if bus) (logior 4 (bus-if bus))))
  (setf (bus-if bus) (logior (bus-if bus)
    (ppu-tick (bus-ppu bus) (if (bus-double-speed bus) (ash cycles -1) cycles) (bus-vram bus) (bus-oam bus)
              (when (bus-hdma-active bus) (lambda () (when (bus-hdma-active bus) (bus-hdma-block bus)))))))
  (incf (bus-dma-clock bus) cycles)
  (loop while (>= (bus-dma-clock bus) 4) do
    (decf (bus-dma-clock bus) 4)
    (when (plusp (bus-dma-delay bus))
      (when (zerop (decf (bus-dma-delay bus)))
        (setf (bus-dma-active bus) t (bus-dma-index bus) 0)))
    (when (bus-dma-active bus)
      (setf (aref (bus-oam bus) (bus-dma-index bus))
            (bus-read bus (wrap16 (+ (bus-dma-source bus) (bus-dma-index bus)))))
      (when (= 160 (incf (bus-dma-index bus))) (setf (bus-dma-active bus) nil))))
  (incf (bus-cycles bus) cycles)
  (incf (bus-hw-cycles bus) (if (bus-double-speed bus) (ash cycles -1) cycles))
  (when (plusp (bus-hdma-stall bus))
    (let ((stall (bus-hdma-stall bus)))
      (setf (bus-hdma-stall bus) 0)
      (bus-tick bus stall))))

(declaim (inline wram-offset))
(defun wram-offset (bus address)
  (+ (logand address #xfff)
     (if (logbitp 12 address) (* 4096 (max 1 (bus-svbk bus))) 0)))

(defun bus-read (bus address)
  (declare (type bus bus) (type u16 address))
  (cond
    ((< address #x8000) (if (bus-cart bus) (mbc-read (bus-cart bus) address)
                           (aref (bus-rom bus) (mod address (length (bus-rom bus))))))
    ((< address #xa000) (aref (bus-vram bus) (+ (* 8192 (bus-vbk bus)) (- address #x8000))))
    ((< address #xc000) (if (bus-cart bus) (mbc-read (bus-cart bus) address)
                           (aref (bus-ram bus) (- address #xa000))))
    ((< address #xfe00) (aref (bus-wram bus) (wram-offset bus address)))
    ((< address #xfea0) (if (bus-dma-active bus) #xff (aref (bus-oam bus) (- address #xfe00))))
    ((< address #xff00) #xff)
    ((= address #xffff) (bus-ie bus))
    ((>= address #xff80) (aref (bus-hram bus) (- address #xff80)))
    ((= address #xff0f) (logior #xe0 (bus-if bus)))
    ((= address #xff4f) (if (eq (bus-mode bus) :cgb) (logior #xfe (bus-vbk bus)) #xff))
    ((= address #xff70) (if (eq (bus-mode bus) :cgb) (logior #xf8 (bus-svbk bus)) #xff))
    ((or (= address #xff4d) (<= #xff51 address #xff55) (<= #xff68 address #xff6c))
     (bus-cgb-read bus address))
    (t (bus-device-read bus address))))

(defun bus-write (bus address value)
  (declare (type bus bus) (type u16 address) (type u8 value))
  (cond
    ((< address #x8000) (when (bus-cart bus) (mbc-write (bus-cart bus) address value)))
    ((< address #xa000) (setf (aref (bus-vram bus) (+ (* 8192 (bus-vbk bus)) (- address #x8000))) value))
    ((< address #xc000) (if (bus-cart bus) (mbc-write (bus-cart bus) address value)
                           (setf (aref (bus-ram bus) (- address #xa000)) value)))
    ((< address #xfe00) (setf (aref (bus-wram bus) (wram-offset bus address)) value))
    ((< address #xfea0) (setf (aref (bus-oam bus) (- address #xfe00)) value))
    ((< address #xff00) nil)
    ((= address #xffff) (setf (bus-ie bus) value))
    ((>= address #xff80) (setf (aref (bus-hram bus) (- address #xff80)) value))
    ((= address #xff0f) (setf (bus-if bus) (logand #x1f value)))
    ((= address #xff4f) (when (eq (bus-mode bus) :cgb) (setf (bus-vbk bus) (logand 1 value))))
    ((= address #xff70) (when (eq (bus-mode bus) :cgb) (setf (bus-svbk bus) (logand 7 value))))
    ((= address #xff02)
     (setf (aref (bus-io bus) 2) value)
     (when (= value #x81)
       (vector-push-extend (aref (bus-io bus) 1) (bus-serial-log bus))
       (setf (aref (bus-io bus) 2) 1 (bus-if bus) (logior 8 (bus-if bus)))))
    ((or (= address #xff4d) (<= #xff51 address #xff55) (<= #xff68 address #xff6c))
     (bus-cgb-write bus address value))
    (t (bus-device-write bus address value)))
  value)
