(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct (cpu (:constructor %make-cpu))
  (a 1 :type u8) (f #xb0 :type u8) (b 0 :type u8) (c #x13 :type u8)
  (d 0 :type u8) (e #xd8 :type u8) (h 1 :type u8) (l #x4d :type u8)
  (sp #xfffe :type u16) (pc #x100 :type u16)
  (ime nil :type boolean) (ime-pending 0 :type fixnum)
  (halted nil :type boolean) (halt-bug nil :type boolean) (stopped nil :type boolean)
  (cycles 0 :type fixnum) (debug-ld-b-b-hit nil :type boolean))

(defun make-cpu (&key (mode :dmg))
  (if (eq mode :cgb)
      (%make-cpu :a #x11 :f #x80 :b 0 :c 0 :d #xff :e #x56 :h 0 :l #x0d)
      (%make-cpu)))

(defmacro define-register-pair (name high low &optional (mask #xffff))
  "レジスタ対を通常の SETF place として公開する。"
  `(progn
     (declaim (inline ,name (setf ,name)))
     (defun ,name (cpu) (logand ,mask (logior (ash (,high cpu) 8) (,low cpu))))
     (defun (setf ,name) (value cpu)
       (let ((word (logand ,mask value)))
         (setf (,high cpu) (ldb (byte 8 8) word) (,low cpu) (ldb (byte 8 0) word)))
       value)))
(define-register-pair cpu-af cpu-a cpu-f #xfff0)
(define-register-pair cpu-bc cpu-b cpu-c)
(define-register-pair cpu-de cpu-d cpu-e)
(define-register-pair cpu-hl cpu-h cpu-l)

(defvar *opcodes* (make-array 256 :initial-element nil))
(defvar *cb-opcodes* (make-array 256 :initial-element nil))
(declaim (inline cpu-tick cpu-read cpu-write cpu-fetch8 cpu-fetch16 signed8 cpu-flags))
(defun cpu-tick (cpu bus &optional (cycles 4))
  (incf (cpu-cycles cpu) cycles) (bus-tick bus cycles))
(defun cpu-read (cpu bus address)
  (cpu-tick cpu bus) (bus-read bus address))
(defun cpu-write (cpu bus address value)
  (cpu-tick cpu bus) (bus-write bus address value))
(defun cpu-fetch8 (cpu bus)
  (prog1 (cpu-read cpu bus (cpu-pc cpu)) (setf (cpu-pc cpu) (wrap16 (1+ (cpu-pc cpu))))))
(defun cpu-fetch16 (cpu bus)
  (let ((low (cpu-fetch8 cpu bus))) (logior low (ash (cpu-fetch8 cpu bus) 8))))
(defun signed8 (value) (if (logbitp 7 value) (- value 256) value))
(defun cpu-flags (cpu z n h c)
  (setf (cpu-f cpu) (logior (if z #x80 0) (if n #x40 0) (if h #x20 0) (if c #x10 0))))
(defun cpu-push (cpu bus value)
  (setf (cpu-sp cpu) (wrap16 (1- (cpu-sp cpu))))
  (cpu-write cpu bus (cpu-sp cpu) (ldb (byte 8 8) value))
  (setf (cpu-sp cpu) (wrap16 (1- (cpu-sp cpu))))
  (cpu-write cpu bus (cpu-sp cpu) (wrap8 value)))
(defun cpu-pop (cpu bus)
  (let ((low (cpu-read cpu bus (cpu-sp cpu))))
    (setf (cpu-sp cpu) (wrap16 (1+ (cpu-sp cpu))))
    (prog1 (logior low (ash (cpu-read cpu bus (cpu-sp cpu)) 8))
      (setf (cpu-sp cpu) (wrap16 (1+ (cpu-sp cpu)))))))

(defun cpu-interrupt (cpu bus)
  (setf (cpu-halted cpu) nil (cpu-ime-pending cpu) 0 (cpu-ime cpu) nil)
  (cpu-tick cpu bus 8)
  (let ((pc (cpu-pc cpu)))
    (setf (cpu-sp cpu) (wrap16 (1- (cpu-sp cpu))))
    (cpu-write cpu bus (cpu-sp cpu) (ldb (byte 8 8) pc))
    ;; SP が 0 だった場合、上位バイトの PUSH が IE を変える。
    (let* ((pending (logand #x1f (bus-if bus) (bus-ie bus)))
           (bit (and (plusp pending) (1- (integer-length (logand pending (- pending)))))))
      (setf (cpu-pc cpu) (if bit (+ #x40 (* 8 bit)) 0))
      (when bit (setf (bus-if bus) (set-bit (bus-if bus) bit nil))))
    (setf (cpu-sp cpu) (wrap16 (1- (cpu-sp cpu))))
    (cpu-write cpu bus (cpu-sp cpu) (wrap8 pc)))
  (cpu-tick cpu bus))

(defun cpu-step (cpu bus)
  "割り込み受理または一命令を実行し、消費 T サイクル数を返す。"
  (let ((start (cpu-cycles cpu)) (pending (logand #x1f (bus-ie bus) (bus-if bus))))
    (when (plusp pending) (setf (cpu-halted cpu) nil))
    (cond
      ((or (cpu-stopped cpu) (cpu-halted cpu)) (cpu-tick cpu bus))
      ((and (cpu-ime cpu) (plusp pending)) (cpu-interrupt cpu bus))
      (t
       (when (plusp (cpu-ime-pending cpu))
         (when (zerop (decf (cpu-ime-pending cpu))) (setf (cpu-ime cpu) t)))
       (let ((opcode (cpu-read cpu bus (cpu-pc cpu))))
         (if (cpu-halt-bug cpu) (setf (cpu-halt-bug cpu) nil)
             (setf (cpu-pc cpu) (wrap16 (1+ (cpu-pc cpu)))))
         (when (= opcode #x40) (setf (cpu-debug-ld-b-b-hit cpu) t))
         (funcall (aref *opcodes* opcode) cpu bus))))
    (- (cpu-cycles cpu) start)))

(defun cpu-stop (cpu bus)
  "STOP のパディングを読み飛ばし、準備済みなら CGB のクロックを切り替える。"
  (setf (cpu-pc cpu) (wrap16 (1+ (cpu-pc cpu))))
  (when (and (eq (bus-mode bus) :cgb) (bus-speed-switch-prepared bus))
    (bus-write bus #xff04 0)
    (setf (bus-double-speed bus) (not (bus-double-speed bus))
          (bus-speed-switch-prepared bus) nil)))
