(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct (machine (:constructor %make-machine))
  (cpu (make-cpu) :type cpu) (bus (make-bus) :type bus)
  (frame-count 0 :type fixnum) (frame-target 0 :type fixnum)
  (framebuffer (make-array 23040 :element-type 'u32 :initial-element #xffffffff)
               :type (simple-array (unsigned-byte 32) (23040))))

(defun make-machine (rom-bytes)
  "検証した ROM から独立したマシンを作る。ROM は呼び出し側と共有する。"
  (let* ((header (parse-cartridge-header rom-bytes))
         (mode (if (member (cartridge-header-cgb-flag header) '(#x80 #xc0)) :cgb :dmg))
         (bus (make-bus :mode mode :rom rom-bytes :cart (make-cartridge rom-bytes header))))
    (setf (bus-if bus) 1)
    (%make-machine :cpu (make-cpu :mode mode) :bus bus)))

(defun run-frame (machine)
  "累積目標を使い、命令境界で生じた端数を次のフレームへ引き継ぐ。"
  (let ((bus (machine-bus machine)) (cpu (machine-cpu machine)))
    (incf (machine-frame-target machine) 70224)
    (loop while (< (bus-hw-cycles bus) (machine-frame-target machine)) do (cpu-step cpu bus))
    (incf (machine-frame-count machine)))
  machine)
(defun machine-serial-log (machine) (bus-serial-log (machine-bus machine)))
(defun machine-cpu-registers (machine)
  (let ((cpu (machine-cpu machine)))
    (list :a (cpu-a cpu) :f (cpu-f cpu) :b (cpu-b cpu) :c (cpu-c cpu)
          :d (cpu-d cpu) :e (cpu-e cpu) :h (cpu-h cpu) :l (cpu-l cpu)
          :sp (cpu-sp cpu) :pc (cpu-pc cpu))))
(defun machine-ld-b-b-hit-p (machine) (cpu-debug-ld-b-b-hit (machine-cpu machine)))
(defun machine-read-byte (machine address)
  (declare (optimize (safety 3)))
  (check-type address u16)
  (bus-read (machine-bus machine) address))
(defun set-buttons (machine button-set)
  (declare (ignore machine button-set)) (error "ジョイパッドは未実装です。"))
(defun drain-audio (machine dst)
  (declare (ignore machine dst)) (error "音声出力は未実装です。"))
