(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct (cartridge (:constructor %make-cartridge))
  (rom (make-array 0 :element-type 'u8) :type octets) (header (make-cartridge-header) :type cartridge-header)
  (ram (make-array 0 :element-type 'u8) :type octets)
  ;; バンクレジスタから再計算する派生値。保存形式には含めない。
  (rom-low-base 0 :type fixnum) (rom-high-base #x4000 :type fixnum)
  (ram-dirty nil :type boolean) (mbc-kind :rom-only :type symbol)
  (rom-bank 1 :type u16) (ram-bank 0 :type u8) (bank-high 0 :type u8)
  (ram-enabled nil :type boolean) (banking-mode 0 :type u8)
  (rtc (make-array 5 :element-type 'u8 :initial-element 0) :type octets)
  (latched-rtc (make-array 5 :element-type 'u8 :initial-element 0) :type octets)
  (latch-prepared nil :type boolean) (rtc-base-unix 0 :type integer))
(defun make-cartridge (rom &optional (header (parse-cartridge-header rom)))
  (let ((cart (%make-cartridge :rom rom :header header :mbc-kind (cartridge-header-mbc-kind header)
                              :ram (make-array (cartridge-header-ram-size header) :element-type 'u8 :initial-element 0))))
    (mbc-refresh-rom-windows cart)
    cart))

(defun mbc-rom-offset (cart address)
  (let* ((kind (cartridge-mbc-kind cart))
         (bank (if (< address #x4000)
                   (if (and (eq kind :mbc1) (= 1 (cartridge-banking-mode cart)))
                       (ash (cartridge-bank-high cart) 5) 0)
                   (case kind
                     (:rom-only 1)
                     (:mbc1 (logior (ash (cartridge-bank-high cart) 5) (cartridge-rom-bank cart)))
                     (otherwise (cartridge-rom-bank cart))))))
    (+ (* (logand bank (1- (ash (cartridge-header-rom-size (cartridge-header cart)) -14))) #x4000)
       (logand address #x3fff))))
(defun mbc-refresh-rom-windows (cart)
  "バンク変更と状態復元時だけ ROM の先頭位置を計算する。"
  (setf (cartridge-rom-low-base cart) (mbc-rom-offset cart 0)
        (cartridge-rom-high-base cart) (mbc-rom-offset cart #x4000)))
(declaim (inline mbc-read-rom))
(defun mbc-read-rom (cart address)
  (declare (type cartridge cart) (type u16 address))
  (aref (cartridge-rom cart)
        (+ (if (< address #x4000) (cartridge-rom-low-base cart) (cartridge-rom-high-base cart))
           (logand address #x3fff))))
(defun mbc-ram-offset (cart address)
  (let ((bank (if (eq (cartridge-mbc-kind cart) :mbc1)
                  (if (= 1 (cartridge-banking-mode cart)) (cartridge-bank-high cart) 0)
                  (cartridge-ram-bank cart))))
    (logand (1- (length (cartridge-ram cart))) (+ (* bank #x2000) (logand address #x1fff)))))
(defun mbc-read (cart address)
  (declare (type cartridge cart) (type u16 address))
  (cond
    ((< address #x8000) (mbc-read-rom cart address))
    ((or (not (<= #xa000 address #xbfff)) (not (cartridge-ram-enabled cart))) #xff)
    ((eq (cartridge-mbc-kind cart) :mbc2)
     (logior #xf0 (aref (cartridge-ram cart) (logand address #x1ff))))
    ((and (eq (cartridge-mbc-kind cart) :mbc3) (>= (cartridge-ram-bank cart) 4))
     (if (and (<= 8 (cartridge-ram-bank cart) 12) (cartridge-header-rtc-p (cartridge-header cart)))
         (aref (cartridge-latched-rtc cart) (- (cartridge-ram-bank cart) 8)) #xff))
    ((zerop (length (cartridge-ram cart))) #xff)
    (t (aref (cartridge-ram cart) (mbc-ram-offset cart address)))))
(defun mbc-write (cart address value)
  (declare (type cartridge cart) (type u16 address) (type u8 value))
  (let ((kind (cartridge-mbc-kind cart)))
    (cond
      ((eq kind :rom-only) nil)
      ((and (eq kind :mbc2) (< address #x4000))
       (if (logbitp 8 address) (setf (cartridge-rom-bank cart) (max 1 (logand 15 value)))
           (setf (cartridge-ram-enabled cart) (= #x0a (logand 15 value)))))
      ((< address #x2000) (setf (cartridge-ram-enabled cart) (= #x0a (logand 15 value))))
      ((< address #x4000)
       (setf (cartridge-rom-bank cart)
             (case kind
               (:mbc1 (max 1 (logand 31 value))) (:mbc3 (max 1 (logand 127 value)))
               (:mbc5 (if (< address #x3000)
                          (logior (logand #x100 (cartridge-rom-bank cart)) value)
                          (logior (logand #xff (cartridge-rom-bank cart)) (ash (logand 1 value) 8)))))))
      ((< address #x6000)
       (case kind
         (:mbc1 (setf (cartridge-bank-high cart) (logand 3 value)))
         (:mbc3 (setf (cartridge-ram-bank cart) value))
         (:mbc5 (setf (cartridge-ram-bank cart) (logand 15 value)))))
      ((< address #x8000)
       (case kind
         (:mbc1 (setf (cartridge-banking-mode cart) (logand 1 value)))
         (:mbc3
          (when (and (= value 1) (cartridge-latch-prepared cart))
            (replace (cartridge-latched-rtc cart) (cartridge-rtc cart)))
          (setf (cartridge-latch-prepared cart) (zerop value)))))
      ((and (<= #xa000 address #xbfff) (cartridge-ram-enabled cart))
       (cond
         ((and (eq kind :mbc3) (>= (cartridge-ram-bank cart) 4))
          (when (and (<= 8 (cartridge-ram-bank cart) 12) (cartridge-header-rtc-p (cartridge-header cart)))
            (let ((index (- (cartridge-ram-bank cart) 8)))
              (setf (aref (cartridge-rtc cart) index)
                    (case index ((0 1) (mod value 60)) (2 (mod value 24)) (3 value) (4 (logand #xc1 value)))))))
         ((plusp (length (cartridge-ram cart)))
          (setf (aref (cartridge-ram cart) (if (eq kind :mbc2) (logand address #x1ff) (mbc-ram-offset cart address)))
                (if (eq kind :mbc2) (logand 15 value) value)
                (cartridge-ram-dirty cart) t))))))
  (when (< address #x8000) (mbc-refresh-rom-windows cart)))
(defun mbc-sync-wall-clock (cart unix-seconds)
  "外部から供給された時刻差のみを進め、コア自身は時計を読まない。"
  (when (and (eq (cartridge-mbc-kind cart) :mbc3) (cartridge-header-rtc-p (cartridge-header cart)))
    (let ((previous (cartridge-rtc-base-unix cart)) (rtc (cartridge-rtc cart)))
      (setf (cartridge-rtc-base-unix cart) unix-seconds)
      (when (and (plusp previous) (> unix-seconds previous) (not (logbitp 6 (aref rtc 4))))
        (let* ((day (logior (aref rtc 3) (ash (logand 1 (aref rtc 4)) 8)))
               (total (+ (- unix-seconds previous) (aref rtc 0) (* 60 (aref rtc 1))
                         (* 3600 (aref rtc 2)) (* 86400 day)))
               (days (floor total 86400)))
          (setf (aref rtc 0) (mod total 60) (aref rtc 1) (mod (floor total 60) 60)
                (aref rtc 2) (mod (floor total 3600) 24) (aref rtc 3) (logand days #xff)
                (aref rtc 4) (logior (if (or (logbitp 7 (aref rtc 4)) (>= days 512)) #x80 0)
                                    (ldb (byte 1 8) days))))))))
