(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(declaim (inline alu-add alu-sub alu-inc alu-dec))
(defun alu-add (cpu value carry)
  (let* ((a (cpu-a cpu)) (sum (+ a value carry)))
    (setf (cpu-a cpu) (wrap8 sum))
    (cpu-flags cpu (zerop (cpu-a cpu)) nil (> (+ (logand a 15) (logand value 15) carry) 15) (> sum 255))))
(defun alu-sub (cpu value carry storep)
  (let* ((a (cpu-a cpu)) (result (wrap8 (- a value carry))))
    (cpu-flags cpu (zerop result) t (< (logand a 15) (+ (logand value 15) carry)) (< a (+ value carry)))
    (when storep (setf (cpu-a cpu) result))))
(defun alu-inc (cpu value)
  (let ((result (wrap8 (1+ value))))
    (cpu-flags cpu (zerop result) nil (= (logand value 15) 15) (logbitp 4 (cpu-f cpu))) result))
(defun alu-dec (cpu value)
  (let ((result (wrap8 (1- value))))
    (cpu-flags cpu (zerop result) t (zerop (logand value 15)) (logbitp 4 (cpu-f cpu))) result))
(defun cpu-daa (cpu)
  (let* ((a (cpu-a cpu)) (n (logbitp 6 (cpu-f cpu))) (c (logbitp 4 (cpu-f cpu)))
         (correction (if (or (logbitp 5 (cpu-f cpu)) (and (not n) (> (logand a 15) 9))) 6 0)))
    (when (or c (and (not n) (> a #x99))) (setf correction (logior correction #x60) c t))
    (setf (cpu-a cpu) (wrap8 (if n (- a correction) (+ a correction))))
    (cpu-flags cpu (zerop (cpu-a cpu)) n nil c)))
(defun cpu-sp-offset (cpu bus)
  (let ((value (cpu-fetch8 cpu bus)) (sp (cpu-sp cpu)))
    (cpu-flags cpu nil nil (> (+ (logand sp 15) (logand value 15)) 15)
               (> (+ (logand sp 255) value) 255))
    (wrap16 (+ sp (signed8 value)))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defun register-form (index)
    (if (= index 6) '(cpu-read cpu bus (cpu-hl cpu))
        `(,(nth index '(cpu-b cpu-c cpu-d cpu-e cpu-h cpu-l nil cpu-a)) cpu)))
  (defun store-register-form (index value)
    (if (= index 6) `(cpu-write cpu bus (cpu-hl cpu) ,value)
        `(setf ,(register-form index) ,value)))
  (defun pair-form (index &optional stackp)
    `(,(nth index (if stackp '(cpu-bc cpu-de cpu-hl cpu-af) '(cpu-bc cpu-de cpu-hl cpu-sp))) cpu))
  (defun condition-form (index)
    (let ((form `(logbitp ,(if (< index 2) 7 4) (cpu-f cpu))))
      (if (evenp index) `(not ,form) form)))
  (defun alu-form (index value)
    (case index
      (0 `(alu-add cpu ,value 0))
      (1 `(alu-add cpu ,value (if (logbitp 4 (cpu-f cpu)) 1 0)))
      (2 `(alu-sub cpu ,value 0 t))
      (3 `(alu-sub cpu ,value (if (logbitp 4 (cpu-f cpu)) 1 0) t))
      (7 `(alu-sub cpu ,value 0 nil))
      (otherwise `(progn
                    (setf (cpu-a cpu) (,(ecase index (4 'logand) (5 'logxor) (6 'logior)) (cpu-a cpu) ,value))
                    (cpu-flags cpu (zerop (cpu-a cpu)) nil ,(= index 4) nil)))))
  (defun rotate-form (operation value &optional accumulatorp)
    `(let* ((v ,value) (carry (logbitp ,(if (member operation '(0 2 4)) 7 0) v))
            (result (wrap8 ,(case operation
                              (0 '(logior (ash v 1) (if carry 1 0)))
                              (1 '(logior (ash v -1) (if carry 128 0)))
                              (2 '(logior (ash v 1) (if (logbitp 4 (cpu-f cpu)) 1 0)))
                              (3 '(logior (ash v -1) (if (logbitp 4 (cpu-f cpu)) 128 0)))
                              (4 '(ash v 1)) (5 '(logior (ash v -1) (logand v 128)))
                              (6 '(logior (ash v 4) (ash v -4))) (7 '(ash v -1))))))
       (cpu-flags cpu ,(unless accumulatorp '(zerop result)) nil nil ,(unless (= operation 6) 'carry))
       result))
  (defun cb-form (opcode)
    (let ((group (ash opcode -6)) (bit (ldb (byte 3 3) opcode)) (index (logand opcode 7)))
      (case group
        (0 (store-register-form index (rotate-form bit (register-form index))))
        (1 `(cpu-flags cpu (not (logbitp ,bit ,(register-form index))) nil t (logbitp 4 (cpu-f cpu))))
        (2 (store-register-form index `(logand ,(logxor #xff (ash 1 bit)) ,(register-form index))))
        (3 (store-register-form index `(logior ,(ash 1 bit) ,(register-form index)))))))
  (defun base-opcode-form (opcode)
    (let* ((row (ldb (byte 3 3) opcode)) (col (logand opcode 7))
           (pair (pair-form (ash row -1))) (illegal '(setf (cpu-stopped cpu) t)))
      (cond
        ((<= #x40 opcode #x7f)
         (if (= opcode #x76)
             '(progn
                (when (plusp (cpu-ime-pending cpu)) (setf (cpu-ime cpu) t (cpu-ime-pending cpu) 0))
                (if (and (not (cpu-ime cpu)) (plusp (logand #x1f (bus-if bus) (bus-ie bus))))
                    (setf (cpu-halt-bug cpu) t) (setf (cpu-halted cpu) t)))
             (store-register-form row (register-form col))))
        ((<= #x80 opcode #xbf) (alu-form row (register-form col)))
        ((< opcode #x40)
         (case col
           (0 (case row
                (0 nil)
                (1 '(let ((address (cpu-fetch16 cpu bus)))
                      (cpu-write cpu bus address (wrap8 (cpu-sp cpu)))
                      (cpu-write cpu bus (wrap16 (1+ address)) (ldb (byte 8 8) (cpu-sp cpu)))))
                (2 '(setf (cpu-pc cpu) (wrap16 (1+ (cpu-pc cpu)))))
                (otherwise `(let ((offset (cpu-fetch8 cpu bus)))
                              (when ,(if (= row 3) t (condition-form (- row 4)))
                                (setf (cpu-pc cpu) (wrap16 (+ (cpu-pc cpu) (signed8 offset))))
                                (cpu-tick cpu bus))))))
           (1 (if (evenp row) `(setf ,pair (cpu-fetch16 cpu bus))
                  `(let* ((hl (cpu-hl cpu)) (value ,pair) (sum (+ hl value)))
                     (cpu-flags cpu (logbitp 7 (cpu-f cpu)) nil
                                (> (+ (logand hl #xfff) (logand value #xfff)) #xfff) (> sum #xffff))
                     (setf (cpu-hl cpu) (wrap16 sum)) (cpu-tick cpu bus))))
           (2 `(let ((address ,(cond ((< row 2) '(cpu-bc cpu)) ((< row 4) '(cpu-de cpu)) (t '(cpu-hl cpu)))))
                 ,(if (evenp row) '(cpu-write cpu bus address (cpu-a cpu))
                      '(setf (cpu-a cpu) (cpu-read cpu bus address)))
                 ,(when (>= row 4) `(setf (cpu-hl cpu) (wrap16 (,(if (< row 6) '1+ '1-) address))))))
           (3 `(progn (setf ,pair (wrap16 (,(if (evenp row) '1+ '1-) ,pair))) (cpu-tick cpu bus)))
           (4 (store-register-form row `(alu-inc cpu ,(register-form row))))
           (5 (store-register-form row `(alu-dec cpu ,(register-form row))))
           (6 (store-register-form row '(cpu-fetch8 cpu bus)))
           (7 (case row
                ((0 1 2 3) `(setf (cpu-a cpu) ,(rotate-form row '(cpu-a cpu) t)))
                (4 '(cpu-daa cpu))
                (5 '(setf (cpu-a cpu) (logxor #xff (cpu-a cpu)) (cpu-f cpu) (logior #x60 (logand #x90 (cpu-f cpu)))))
                (6 '(setf (cpu-f cpu) (logior #x10 (logand #x80 (cpu-f cpu)))))
                (7 '(setf (cpu-f cpu) (logxor #x10 (logand #x90 (cpu-f cpu)))))))))
        (t
         (case col
           (0 (case row
                ((0 1 2 3) `(progn (cpu-tick cpu bus)
                                   (when ,(condition-form row) (setf (cpu-pc cpu) (cpu-pop cpu bus)) (cpu-tick cpu bus))))
                (4 '(let ((address (+ #xff00 (cpu-fetch8 cpu bus)))) (cpu-write cpu bus address (cpu-a cpu))))
                (6 '(setf (cpu-a cpu) (cpu-read cpu bus (+ #xff00 (cpu-fetch8 cpu bus)))))
                (5 '(let ((result (cpu-sp-offset cpu bus))) (cpu-tick cpu bus 8) (setf (cpu-sp cpu) result)))
                (7 '(let ((result (cpu-sp-offset cpu bus))) (cpu-tick cpu bus) (setf (cpu-hl cpu) result)))))
           (1 (if (evenp row) `(setf ,(pair-form (ash row -1) t) (cpu-pop cpu bus))
                  (case row
                    (1 '(progn (setf (cpu-pc cpu) (cpu-pop cpu bus)) (cpu-tick cpu bus)))
                    (3 '(progn (setf (cpu-pc cpu) (cpu-pop cpu bus)) (cpu-tick cpu bus) (setf (cpu-ime cpu) t)))
                    (5 '(setf (cpu-pc cpu) (cpu-hl cpu)))
                    (7 '(progn (cpu-tick cpu bus) (setf (cpu-sp cpu) (cpu-hl cpu)))))))
           (2 (if (< row 4)
                  `(let ((address (cpu-fetch16 cpu bus)))
                     (when ,(condition-form row) (setf (cpu-pc cpu) address) (cpu-tick cpu bus)))
                  `(let ((address ,(if (member row '(4 6)) '(+ #xff00 (cpu-c cpu)) '(cpu-fetch16 cpu bus))))
                     ,(if (< row 6) '(cpu-write cpu bus address (cpu-a cpu))
                          '(setf (cpu-a cpu) (cpu-read cpu bus address))))))
           (3 (case row
                (0 '(progn (setf (cpu-pc cpu) (cpu-fetch16 cpu bus)) (cpu-tick cpu bus)))
                (1 '(funcall (aref *cb-opcodes* (cpu-fetch8 cpu bus)) cpu bus))
                (6 '(setf (cpu-ime cpu) nil (cpu-ime-pending cpu) 0))
                (7 '(setf (cpu-ime-pending cpu) 1)) (otherwise illegal)))
           (4 (if (< row 4)
                  `(let ((address (cpu-fetch16 cpu bus)))
                     (when ,(condition-form row) (cpu-tick cpu bus) (cpu-push cpu bus (cpu-pc cpu)) (setf (cpu-pc cpu) address)))
                  illegal))
           (5 (cond ((evenp row) `(progn (cpu-tick cpu bus) (cpu-push cpu bus ,(pair-form (ash row -1) t))))
                    ((= row 1) '(let ((address (cpu-fetch16 cpu bus))) (cpu-tick cpu bus) (cpu-push cpu bus (cpu-pc cpu)) (setf (cpu-pc cpu) address)))
                    (t illegal)))
           (6 (alu-form row '(cpu-fetch8 cpu bus)))
           (7 `(progn (cpu-tick cpu bus) (cpu-push cpu bus (cpu-pc cpu)) (setf (cpu-pc cpu) ,(logand opcode #x38))))))))))

(defmacro define-instruction-tables ()
  "命令のビット規則をコンパイル時に展開し、実行時は関数ベクタで直接選ぶ。"
  `(progn
     ,@(loop for opcode below 256 append
             `((setf (aref *opcodes* ,opcode)
                     (lambda (cpu bus) (declare (type cpu cpu) (type bus bus) (ignorable cpu bus))
                       ,(base-opcode-form opcode)))
               (setf (aref *cb-opcodes* ,opcode)
                     (lambda (cpu bus) (declare (type cpu cpu) (type bus bus) (ignorable cpu bus))
                       ,(cb-form opcode)))))))
(define-instruction-tables)
