(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct ppu
  (cgb nil :type boolean) (bcps 0 :type u8) (ocps 0 :type u8) (opri 0 :type u8)
  (bg-palette (make-array 64 :element-type 'u8 :initial-element #xff) :type octets)
  (obj-palette (make-array 64 :element-type 'u8 :initial-element #xff) :type octets)
  ;; 色変換キャッシュと描画の作業領域は保存せず、復元時に再計算する。
  (bg-argb (make-array 32 :element-type 'u32 :initial-element #xffffffff) :type (simple-array (unsigned-byte 32) (32)))
  (obj-argb (make-array 32 :element-type 'u32 :initial-element #xffffffff) :type (simple-array (unsigned-byte 32) (32)))
  (line-sprites (make-array 10 :element-type 'u8 :initial-element 0) :type octets)
  (bg-priority (make-array 160 :element-type 'bit :initial-element 0) :type simple-bit-vector)
  (lcdc 0 :type u8) (stat 0 :type u8) (scy 0 :type u8) (scx 0 :type u8)
  (ly 0 :type u8) (lyc 0 :type u8) (bgp #xfc :type u8)
  (obp0 #xff :type u8) (obp1 #xff :type u8) (wy 0 :type u8) (wx 0 :type u8)
  (mode 0 :type u8) (dot 0 :type fixnum) (window-line 0 :type fixnum)
  (lyc-equal t :type boolean) (stat-line nil :type boolean) (frame-ready nil :type boolean)
  (framebuffer (make-array 23040 :element-type 'u32 :initial-element #xffffffff)
               :type (simple-array (unsigned-byte 32) (23040)))
  (bg-colors (make-array 160 :element-type 'u8 :initial-element 0) :type octets)
  (sprite-owned (make-array 160 :element-type 'bit :initial-element 0) :type simple-bit-vector))

(defun ppu-stat-interrupt (ppu)
  (let ((line (or (and (ppu-lyc-equal ppu) (logbitp 6 (ppu-stat ppu)))
                  (and (/= (ppu-mode ppu) 3) (logbitp (+ 3 (ppu-mode ppu)) (ppu-stat ppu))))))
    (prog1 (and line (not (ppu-stat-line ppu))) (setf (ppu-stat-line ppu) (not (null line))))))
(defun ppu-read (ppu address)
  (case address
    (#xff68 (logior #x40 (ppu-bcps ppu)))
    (#xff6a (logior #x40 (ppu-ocps ppu)))
    (#xff69 (if (= (ppu-mode ppu) 3) #xff (aref (ppu-bg-palette ppu) (logand 63 (ppu-bcps ppu)))))
    (#xff6b (if (= (ppu-mode ppu) 3) #xff (aref (ppu-obj-palette ppu) (logand 63 (ppu-ocps ppu)))))
    (#xff6c (logior #xfe (ppu-opri ppu)))
    (#xff41 (logior #x80 (ppu-stat ppu) (ppu-mode ppu) (if (ppu-lyc-equal ppu) 4 0)))
    (otherwise
     (funcall (case address (#xff40 #'ppu-lcdc) (#xff42 #'ppu-scy) (#xff43 #'ppu-scx)
                    (#xff44 #'ppu-ly) (#xff45 #'ppu-lyc) (#xff47 #'ppu-bgp)
                    (#xff48 #'ppu-obp0) (#xff49 #'ppu-obp1) (#xff4a #'ppu-wy) (#xff4b #'ppu-wx)) ppu))))
(defun ppu-write (ppu address value)
  (case address
    (#xff68 (setf (ppu-bcps ppu) (logand #xbf value)))
    (#xff6a (setf (ppu-ocps ppu) (logand #xbf value)))
    (#xff6c (setf (ppu-opri ppu) (logand 1 value)))
    ((#xff69 #xff6b)
     (let* ((obj (= address #xff6b)) (index (if obj (ppu-ocps ppu) (ppu-bcps ppu))))
       (unless (= (ppu-mode ppu) 3)
         (setf (aref (if obj (ppu-obj-palette ppu) (ppu-bg-palette ppu)) (logand 63 index)) value)
         (ppu-refresh-color ppu obj (ash (logand 63 index) -1)))
       (when (logbitp 7 index)
         (let ((next (logior #x80 (logand 63 (1+ index)))))
           (if obj (setf (ppu-ocps ppu) next) (setf (ppu-bcps ppu) next))))))
    (#xff40
     (let ((old (logbitp 7 (ppu-lcdc ppu))) (new (logbitp 7 value)))
       (setf (ppu-lcdc ppu) value)
       (unless (eq old new)
         (setf (ppu-ly ppu) 0 (ppu-dot ppu) 0 (ppu-mode ppu) (if new 2 0))
         (when new (setf (ppu-window-line ppu) 0 (ppu-lyc-equal ppu) (= 0 (ppu-lyc ppu)))))))
    (#xff41 (setf (ppu-stat ppu) (logand #x78 value)))
    (#xff42 (setf (ppu-scy ppu) value)) (#xff43 (setf (ppu-scx ppu) value))
    (#xff45 (setf (ppu-lyc ppu) value)
             (when (logbitp 7 (ppu-lcdc ppu)) (setf (ppu-lyc-equal ppu) (= value (ppu-ly ppu)))))
    (#xff47 (setf (ppu-bgp ppu) value)) (#xff48 (setf (ppu-obp0 ppu) value))
    (#xff49 (setf (ppu-obp1 ppu) value)) (#xff4a (setf (ppu-wy ppu) value)) (#xff4b (setf (ppu-wx ppu) value)))
  (ppu-stat-interrupt ppu))

(declaim (inline dmg-color tile-pixel))
(defun dmg-color (palette color)
  (aref #(#xffffffff #xffaaaaaa #xff555555 #xff000000) (ldb (byte 2 (* color 2)) palette)))
(defun tile-pixel (vram address x)
  (logior (ldb (byte 1 (- 7 x)) (aref vram address))
          (ash (ldb (byte 1 (- 7 x)) (aref vram (1+ address))) 1)))
(defun cgb-color (palette index)
  (let* ((offset (* 2 index))
         (raw (logior (aref palette offset) (ash (aref palette (1+ offset)) 8))))
    (flet ((expand (shift) (let ((v (ldb (byte 5 shift) raw))) (logior (ash v 3) (ash v -2)))))
      (logior #xff000000 (ash (expand 0) 16) (ash (expand 5) 8) (expand 10)))))
(defun ppu-refresh-color (ppu obj index)
  (declare (type ppu ppu) (type (integer 0 31) index))
  (setf (aref (if obj (ppu-obj-argb ppu) (ppu-bg-argb ppu)) index)
        (cgb-color (if obj (ppu-obj-palette ppu) (ppu-bg-palette ppu)) index)))
(defun ppu-refresh-palettes (ppu)
  (dotimes (i 32) (ppu-refresh-color ppu nil i) (ppu-refresh-color ppu t i)))

(defun ppu-select-sprites (ppu oam)
  "可視スプライトを作業配列へ集める。DMGの同じXではOAM順を保つ。"
  (declare (type ppu ppu) (type octets oam))
  (let ((count 0) (sprites (ppu-line-sprites ppu))
        (height (if (logbitp 2 (ppu-lcdc ppu)) 16 8)) (ly (ppu-ly ppu))
        (sort-by-x (or (not (ppu-cgb ppu)) (= (ppu-opri ppu) 1))))
    (declare (type fixnum count height ly))
    (when (logbitp 1 (ppu-lcdc ppu))
      (loop for i fixnum from 0 below 160 by 4 do
        (when (<= 0 (- (+ ly 16) (aref oam i)) (1- height))
          (let ((position count))
            (declare (type fixnum position))
            (when sort-by-x
              (loop while (and (plusp position)
                               (> (aref oam (1+ (aref sprites (1- position)))) (aref oam (1+ i)))) do
                (setf (aref sprites position) (aref sprites (1- position))) (decf position)))
            (setf (aref sprites position) i))
          (when (= 10 (incf count)) (return)))))
    count))

(defun ppu-render-background (ppu vram scratch-p)
  "タイル行の2バイトを一度読み、窓・スクロール境界で区切って描く。"
  (declare (type ppu ppu) (type octets vram))
  (let* ((ly (ppu-ly ppu)) (lcdc (ppu-lcdc ppu)) (start (* ly 160))
         (cgb (ppu-cgb ppu)) (bg-enabled (or cgb (logbitp 0 lcdc)))
         (frame (ppu-framebuffer ppu)) (colors (ppu-bg-colors ppu)) (priority (ppu-bg-priority ppu))
         (argb (ppu-bg-argb ppu)) (window-left (- (ppu-wx ppu) 7))
         (window (and bg-enabled (logbitp 5 lcdc) (>= ly (ppu-wy ppu)) (< (ppu-wx ppu) 167))))
    (if (not bg-enabled)
        (progn
          (fill frame #xffffffff :start start :end (+ start 160))
          (when scratch-p (fill colors 0) (fill priority 0)))
        (loop with x fixnum = 0 while (< x 160) do
          (let* ((win (and window (>= x window-left)))
                 (sx (if win (- x window-left) (wrap8 (+ x (ppu-scx ppu)))))
                 (sy (if win (ppu-window-line ppu) (wrap8 (+ ly (ppu-scy ppu)))))
                 (col (logand sx 7))
                 (count (min (- 8 col) (- 160 x)))
                 (map (+ (if (logbitp (if win 6 3) lcdc) #x1c00 #x1800) (* 32 (ash sy -3)) (ash sx -3)))
                 (tile (aref vram map)) (attr (if cgb (aref vram (+ #x2000 map)) 0))
                 (row (logand sy 7))
                 (address (+ (if (logbitp 4 lcdc) (* tile 16) (+ #x1000 (* (if (< tile 128) tile (- tile 256)) 16)))
                             (* 2 (if (logbitp 6 attr) (- 7 row) row)) (if (logbitp 3 attr) #x2000 0)))
                 (low (aref vram address)) (high (aref vram (1+ address)))
                 (flip (logbitp 5 attr)) (palette (* 4 (logand 7 attr)))
                 (bg-priority (if (logbitp 7 attr) 1 0)))
            (declare (type fixnum sx sy col count map row address palette))
            ;; ウィンドウがタイルの途中で始まる場合、BG側をそこで止める。
            (when (and window (not win)) (setf count (min count (- window-left x))))
            (dotimes (i count)
              (let* ((bit (if flip (+ col i) (- 7 col i)))
                     (color (logior (ldb (byte 1 bit) low) (ash (ldb (byte 1 bit) high) 1)))
                     (pixel (+ x i)))
                (when scratch-p
                  (setf (aref colors pixel) color (aref priority pixel) bg-priority))
                (setf (aref frame (+ start pixel))
                      (if cgb (aref argb (+ palette color)) (dmg-color (ppu-bgp ppu) color)))))
            (incf x count))))
    (when window (incf (ppu-window-line ppu)))))

(defun ppu-render-sprites (ppu vram oam count)
  (declare (type ppu ppu) (type octets vram oam) (type fixnum count))
  (let* ((cgb (ppu-cgb ppu)) (ly (ppu-ly ppu)) (lcdc (ppu-lcdc ppu)) (start (* ly 160))
         (height (if (logbitp 2 lcdc) 16 8)) (frame (ppu-framebuffer ppu))
         (owned (ppu-sprite-owned ppu)) (colors (ppu-bg-colors ppu))
         (priority (ppu-bg-priority ppu)) (argb (ppu-obj-argb ppu)))
    (fill owned 0)
    (dotimes (index count)
      (let* ((i (aref (ppu-line-sprites ppu) index))
             (left (- (aref oam (1+ i)) 8)) (attr (aref oam (+ i 3)))
             (row (- (+ ly 16) (aref oam i))) (y (if (logbitp 6 attr) (- height 1 row) row))
             (tile (logand (aref oam (+ i 2)) (if (= height 16) #xfe #xff)))
             (address (+ (* tile 16) (* 2 y) (if (and cgb (logbitp 3 attr)) #x2000 0)))
             (low (aref vram address)) (high (aref vram (1+ address)))
             (palette (* 4 (logand 7 attr))) (flip (logbitp 5 attr)))
        (dotimes (col 8)
          (let ((x (+ left col)))
            (when (and (<= 0 x 159) (zerop (aref owned x)))
              (let* ((bit (if flip col (- 7 col)))
                     (color (logior (ldb (byte 1 bit) low) (ash (ldb (byte 1 bit) high) 1))))
                (unless (zerop color)
                  (setf (aref owned x) 1)
                  (unless (and (plusp (aref colors x))
                               (if cgb (and (logbitp 0 lcdc) (or (logbitp 7 attr) (= 1 (aref priority x))))
                                   (logbitp 7 attr)))
                    (setf (aref frame (+ start x))
                          (if cgb (aref argb (+ palette color))
                              (dmg-color (if (logbitp 4 attr) (ppu-obp1 ppu) (ppu-obp0 ppu)) color)))))))))))))

(defun ppu-render-line (ppu vram oam)
  (declare (type ppu ppu) (type octets vram oam))
  (let ((count (ppu-select-sprites ppu oam)))
    ;; スプライトがないラインでは、重なり判定用の配列への書き込みを省く。
    (ppu-render-background ppu vram (plusp count))
    (when (plusp count) (ppu-render-sprites ppu vram oam count))))

(defun ppu-tick (ppu cycles vram oam &optional hblank-hook)
  "モード境界までまとめて進め、VBlank / STAT の要求ビットを返す。"
  (declare (type ppu ppu) (type fixnum cycles) (type octets vram oam))
  (let ((interrupts 0))
    (when (logbitp 7 (ppu-lcdc ppu))
      (loop while (plusp cycles) do
        (let* ((boundary (case (ppu-mode ppu) (2 80) (3 252) (otherwise 456)))
               (step (min cycles (- boundary (ppu-dot ppu)))))
          (incf (ppu-dot ppu) step) (decf cycles step)
          (when (= boundary (ppu-dot ppu))
            (case boundary
              (80 (setf (ppu-mode ppu) 3))
              (252 (setf (ppu-mode ppu) 0) (ppu-render-line ppu vram oam)
                   (when hblank-hook (funcall hblank-hook)))
              (456
               (setf (ppu-dot ppu) 0 (ppu-ly ppu) (mod (1+ (ppu-ly ppu)) 154)
                     (ppu-lyc-equal ppu) (= (ppu-ly ppu) (ppu-lyc ppu))
                     (ppu-mode ppu) (if (>= (ppu-ly ppu) 144) 1 2))
               (when (zerop (ppu-ly ppu)) (setf (ppu-window-line ppu) 0))
               (when (= (ppu-ly ppu) 144) (setf interrupts (logior interrupts 1) (ppu-frame-ready ppu) t))))
            (when (ppu-stat-interrupt ppu) (setf interrupts (logior interrupts 2)))))))
    interrupts))
