(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct ppu
  (lcdc 0 :type u8) (stat 0 :type u8) (scy 0 :type u8) (scx 0 :type u8)
  (ly 0 :type u8) (lyc 0 :type u8) (bgp #xfc :type u8)
  (obp0 #xff :type u8) (obp1 #xff :type u8) (wy 0 :type u8) (wx 0 :type u8)
  (mode 0 :type u8) (dot 0 :type fixnum) (window-line 0 :type fixnum)
  (lyc-equal t :type boolean) (stat-line nil :type boolean) (frame-ready nil :type boolean)
  (framebuffer (make-array 23040 :element-type 'u32 :initial-element #xffffffff)
               :type (simple-array (unsigned-byte 32) (23040)))
  (bg-colors (make-array 160 :element-type 'u8 :initial-element 0) :type octets)
  (sprite-owned (make-array 160 :element-type 'bit :initial-element 0) :type simple-bit-vector))

(defun ppu-stat-interrupt (ppu)
  (let ((line (or (and (ppu-lyc-equal ppu) (logbitp 6 (ppu-stat ppu)))
                  (and (/= (ppu-mode ppu) 3) (logbitp (+ 3 (ppu-mode ppu)) (ppu-stat ppu))))))
    (prog1 (and line (not (ppu-stat-line ppu))) (setf (ppu-stat-line ppu) (not (null line))))))
(defun ppu-read (ppu address)
  (case address
    (#xff41 (logior #x80 (ppu-stat ppu) (ppu-mode ppu) (if (ppu-lyc-equal ppu) 4 0)))
    (otherwise
     (funcall (case address (#xff40 #'ppu-lcdc) (#xff42 #'ppu-scy) (#xff43 #'ppu-scx)
                    (#xff44 #'ppu-ly) (#xff45 #'ppu-lyc) (#xff47 #'ppu-bgp)
                    (#xff48 #'ppu-obp0) (#xff49 #'ppu-obp1) (#xff4a #'ppu-wy) (#xff4b #'ppu-wx)) ppu))))
(defun ppu-write (ppu address value)
  (case address
    (#xff40
     (let ((old (logbitp 7 (ppu-lcdc ppu))) (new (logbitp 7 value)))
       (setf (ppu-lcdc ppu) value)
       (unless (eq old new)
         (setf (ppu-ly ppu) 0 (ppu-dot ppu) 0 (ppu-mode ppu) (if new 2 0))
         (when new (setf (ppu-window-line ppu) 0 (ppu-lyc-equal ppu) (= 0 (ppu-lyc ppu)))))))
    (#xff41 (setf (ppu-stat ppu) (logand #x78 value)))
    (#xff42 (setf (ppu-scy ppu) value)) (#xff43 (setf (ppu-scx ppu) value))
    (#xff45 (setf (ppu-lyc ppu) value)
             (when (logbitp 7 (ppu-lcdc ppu)) (setf (ppu-lyc-equal ppu) (= value (ppu-ly ppu)))))
    (#xff47 (setf (ppu-bgp ppu) value)) (#xff48 (setf (ppu-obp0 ppu) value))
    (#xff49 (setf (ppu-obp1 ppu) value)) (#xff4a (setf (ppu-wy ppu) value)) (#xff4b (setf (ppu-wx ppu) value)))
  (ppu-stat-interrupt ppu))

(declaim (inline dmg-color tile-pixel))
(defun dmg-color (palette color)
  (aref #(#xffffffff #xffaaaaaa #xff555555 #xff000000) (ldb (byte 2 (* color 2)) palette)))
(defun tile-pixel (vram address x)
  (logior (ldb (byte 1 (- 7 x)) (aref vram address))
          (ash (ldb (byte 1 (- 7 x)) (aref vram (1+ address))) 1)))
(defun ppu-render-line (ppu vram oam)
  (let* ((ly (ppu-ly ppu)) (lcdc (ppu-lcdc ppu)) (start (* ly 160))
         (frame (ppu-framebuffer ppu)) (colors (ppu-bg-colors ppu))
         (window (and (logbitp 0 lcdc) (logbitp 5 lcdc) (>= ly (ppu-wy ppu)) (< (ppu-wx ppu) 167))))
    (dotimes (x 160)
      (let ((color 0))
        (when (logbitp 0 lcdc)
          (let* ((win (and window (>= x (- (ppu-wx ppu) 7))))
                 (sx (if win (- x (- (ppu-wx ppu) 7)) (wrap8 (+ x (ppu-scx ppu)))))
                 (sy (if win (ppu-window-line ppu) (wrap8 (+ ly (ppu-scy ppu)))))
                 (map (+ (if (logbitp (if win 6 3) lcdc) #x1c00 #x1800) (* 32 (ash sy -3)) (ash sx -3)))
                 (tile (aref vram map))
                 (address (+ (if (logbitp 4 lcdc) (* tile 16) (+ #x1000 (* (if (< tile 128) tile (- tile 256)) 16)))
                             (* 2 (logand sy 7)))))
            (setf color (tile-pixel vram address (logand sx 7)))))
        (setf (aref colors x) color
              (aref frame (+ start x)) (if (logbitp 0 lcdc) (dmg-color (ppu-bgp ppu) color) #xffffffff))))
    (when window (incf (ppu-window-line ppu)))
    (when (logbitp 1 lcdc)
      (fill (ppu-sprite-owned ppu) 0)
      (let* ((height (if (logbitp 2 lcdc) 16 8))
             (sprites (loop for i from 0 below 160 by 4
                            when (<= 0 (- (+ ly 16) (aref oam i)) (1- height)) collect i into found
                            and count t into count when (= count 10) return found finally (return found))))
        (setf sprites (stable-sort sprites #'< :key (lambda (i) (aref oam (1+ i)))))
        (dolist (i sprites)
          (let* ((left (- (aref oam (+ i 1)) 8)) (attr (aref oam (+ i 3)))
                 (row (- (+ ly 16) (aref oam i)))
                 (y (if (logbitp 6 attr) (- height 1 row) row))
                 (tile (logand (aref oam (+ i 2)) (if (= height 16) #xfe #xff)))
                 (address (+ (* tile 16) (* 2 y))))
            (dotimes (col 8)
              (let ((x (+ left col)))
                (when (and (<= 0 x 159) (zerop (aref (ppu-sprite-owned ppu) x)))
                  (let ((color (tile-pixel vram address (if (logbitp 5 attr) (- 7 col) col))))
                    (unless (zerop color)
                      (setf (aref (ppu-sprite-owned ppu) x) 1)
                      (unless (and (logbitp 7 attr) (plusp (aref colors x)))
                        (setf (aref frame (+ start x)) (dmg-color (if (logbitp 4 attr) (ppu-obp1 ppu) (ppu-obp0 ppu)) color))))))))))))))

(defun ppu-tick (ppu cycles vram oam)
  "モード境界までまとめて進め、VBlank / STAT の要求ビットを返す。"
  (let ((interrupts 0))
    (when (logbitp 7 (ppu-lcdc ppu))
      (loop while (plusp cycles) do
        (let* ((boundary (case (ppu-mode ppu) (2 80) (3 252) (otherwise 456)))
               (step (min cycles (- boundary (ppu-dot ppu)))))
          (incf (ppu-dot ppu) step) (decf cycles step)
          (when (= boundary (ppu-dot ppu))
            (case boundary
              (80 (setf (ppu-mode ppu) 3))
              (252 (setf (ppu-mode ppu) 0) (ppu-render-line ppu vram oam))
              (456
               (setf (ppu-dot ppu) 0 (ppu-ly ppu) (mod (1+ (ppu-ly ppu)) 154)
                     (ppu-lyc-equal ppu) (= (ppu-ly ppu) (ppu-lyc ppu))
                     (ppu-mode ppu) (if (>= (ppu-ly ppu) 144) 1 2))
               (when (zerop (ppu-ly ppu)) (setf (ppu-window-line ppu) 0))
               (when (= (ppu-ly ppu) 144) (setf interrupts (logior interrupts 1) (ppu-frame-ready ppu) t))))
            (when (ppu-stat-interrupt ppu) (setf interrupts (logior interrupts 2)))))))
    interrupts))
