(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct ppu
  (cgb nil :type boolean) (bcps 0 :type u8) (ocps 0 :type u8) (opri 0 :type u8)
  (bg-palette (make-array 64 :element-type 'u8 :initial-element #xff) :type octets)
  (obj-palette (make-array 64 :element-type 'u8 :initial-element #xff) :type octets)
  (bg-priority (make-array 160 :element-type 'bit :initial-element 0) :type simple-bit-vector)
  (lcdc 0 :type u8) (stat 0 :type u8) (scy 0 :type u8) (scx 0 :type u8)
  (ly 0 :type u8) (lyc 0 :type u8) (bgp #xfc :type u8)
  (obp0 #xff :type u8) (obp1 #xff :type u8) (wy 0 :type u8) (wx 0 :type u8)
  (mode 0 :type u8) (dot 0 :type fixnum) (window-line 0 :type fixnum)
  (lyc-equal t :type boolean) (stat-line nil :type boolean) (frame-ready nil :type boolean)
  (framebuffer (make-array 23040 :element-type 'u32 :initial-element #xffffffff)
               :type (simple-array (unsigned-byte 32) (23040)))
  (bg-colors (make-array 160 :element-type 'u8 :initial-element 0) :type octets)
  (sprite-owned (make-array 160 :element-type 'bit :initial-element 0) :type simple-bit-vector))

(defun ppu-stat-interrupt (ppu)
  (let ((line (or (and (ppu-lyc-equal ppu) (logbitp 6 (ppu-stat ppu)))
                  (and (/= (ppu-mode ppu) 3) (logbitp (+ 3 (ppu-mode ppu)) (ppu-stat ppu))))))
    (prog1 (and line (not (ppu-stat-line ppu))) (setf (ppu-stat-line ppu) (not (null line))))))
(defun ppu-read (ppu address)
  (case address
    (#xff68 (logior #x40 (ppu-bcps ppu)))
    (#xff6a (logior #x40 (ppu-ocps ppu)))
    (#xff69 (if (= (ppu-mode ppu) 3) #xff (aref (ppu-bg-palette ppu) (logand 63 (ppu-bcps ppu)))))
    (#xff6b (if (= (ppu-mode ppu) 3) #xff (aref (ppu-obj-palette ppu) (logand 63 (ppu-ocps ppu)))))
    (#xff6c (logior #xfe (ppu-opri ppu)))
    (#xff41 (logior #x80 (ppu-stat ppu) (ppu-mode ppu) (if (ppu-lyc-equal ppu) 4 0)))
    (otherwise
     (funcall (case address (#xff40 #'ppu-lcdc) (#xff42 #'ppu-scy) (#xff43 #'ppu-scx)
                    (#xff44 #'ppu-ly) (#xff45 #'ppu-lyc) (#xff47 #'ppu-bgp)
                    (#xff48 #'ppu-obp0) (#xff49 #'ppu-obp1) (#xff4a #'ppu-wy) (#xff4b #'ppu-wx)) ppu))))
(defun ppu-write (ppu address value)
  (case address
    (#xff68 (setf (ppu-bcps ppu) (logand #xbf value)))
    (#xff6a (setf (ppu-ocps ppu) (logand #xbf value)))
    (#xff6c (setf (ppu-opri ppu) (logand 1 value)))
    ((#xff69 #xff6b)
     (let* ((obj (= address #xff6b)) (index (if obj (ppu-ocps ppu) (ppu-bcps ppu))))
       (unless (= (ppu-mode ppu) 3)
         (setf (aref (if obj (ppu-obj-palette ppu) (ppu-bg-palette ppu)) (logand 63 index)) value))
       (when (logbitp 7 index)
         (let ((next (logior #x80 (logand 63 (1+ index)))))
           (if obj (setf (ppu-ocps ppu) next) (setf (ppu-bcps ppu) next))))))
    (#xff40
     (let ((old (logbitp 7 (ppu-lcdc ppu))) (new (logbitp 7 value)))
       (setf (ppu-lcdc ppu) value)
       (unless (eq old new)
         (setf (ppu-ly ppu) 0 (ppu-dot ppu) 0 (ppu-mode ppu) (if new 2 0))
         (when new (setf (ppu-window-line ppu) 0 (ppu-lyc-equal ppu) (= 0 (ppu-lyc ppu)))))))
    (#xff41 (setf (ppu-stat ppu) (logand #x78 value)))
    (#xff42 (setf (ppu-scy ppu) value)) (#xff43 (setf (ppu-scx ppu) value))
    (#xff45 (setf (ppu-lyc ppu) value)
             (when (logbitp 7 (ppu-lcdc ppu)) (setf (ppu-lyc-equal ppu) (= value (ppu-ly ppu)))))
    (#xff47 (setf (ppu-bgp ppu) value)) (#xff48 (setf (ppu-obp0 ppu) value))
    (#xff49 (setf (ppu-obp1 ppu) value)) (#xff4a (setf (ppu-wy ppu) value)) (#xff4b (setf (ppu-wx ppu) value)))
  (ppu-stat-interrupt ppu))

(declaim (inline dmg-color tile-pixel))
(defun dmg-color (palette color)
  (aref #(#xffffffff #xffaaaaaa #xff555555 #xff000000) (ldb (byte 2 (* color 2)) palette)))
(defun tile-pixel (vram address x)
  (logior (ldb (byte 1 (- 7 x)) (aref vram address))
          (ash (ldb (byte 1 (- 7 x)) (aref vram (1+ address))) 1)))
(defun cgb-color (palette index)
  (let* ((offset (* 2 index))
         (raw (logior (aref palette offset) (ash (aref palette (1+ offset)) 8))))
    (flet ((expand (shift) (let ((v (ldb (byte 5 shift) raw))) (logior (ash v 3) (ash v -2)))))
      (logior #xff000000 (ash (expand 0) 16) (ash (expand 5) 8) (expand 10)))))
(defun ppu-render-line (ppu vram oam)
  (let* ((ly (ppu-ly ppu)) (lcdc (ppu-lcdc ppu)) (start (* ly 160))
         (cgb (ppu-cgb ppu)) (bg-enabled (or (ppu-cgb ppu) (logbitp 0 lcdc)))
         (frame (ppu-framebuffer ppu)) (colors (ppu-bg-colors ppu))
         (window (and bg-enabled (logbitp 5 lcdc) (>= ly (ppu-wy ppu)) (< (ppu-wx ppu) 167))))
    (dotimes (x 160)
      (let ((color 0) (attribute 0))
        (when bg-enabled
          (let* ((win (and window (>= x (- (ppu-wx ppu) 7))))
                 (sx (if win (- x (- (ppu-wx ppu) 7)) (wrap8 (+ x (ppu-scx ppu)))))
                 (sy (if win (ppu-window-line ppu) (wrap8 (+ ly (ppu-scy ppu)))))
                 (map (+ (if (logbitp (if win 6 3) lcdc) #x1c00 #x1800) (* 32 (ash sy -3)) (ash sx -3)))
                 (tile (aref vram map))
                 (attr (if cgb (aref vram (+ #x2000 map)) 0))
                 (row (logand sy 7)) (col (logand sx 7))
                 (address (+ (if (logbitp 4 lcdc) (* tile 16) (+ #x1000 (* (if (< tile 128) tile (- tile 256)) 16)))
                             (* 2 (if (logbitp 6 attr) (- 7 row) row))
                             (if (logbitp 3 attr) #x2000 0))))
            (setf attribute attr color (tile-pixel vram address (if (logbitp 5 attr) (- 7 col) col)))))
        (setf (aref colors x) color
              (aref (ppu-bg-priority ppu) x) (if (logbitp 7 attribute) 1 0)
              (aref frame (+ start x))
              (cond (cgb (cgb-color (ppu-bg-palette ppu) (+ (* 4 (logand 7 attribute)) color)))
                    (bg-enabled (dmg-color (ppu-bgp ppu) color)) (t #xffffffff)))))
    (when window (incf (ppu-window-line ppu)))
    (when (logbitp 1 lcdc)
      (fill (ppu-sprite-owned ppu) 0)
      (let* ((height (if (logbitp 2 lcdc) 16 8))
             (sprites (loop for i from 0 below 160 by 4
                            when (<= 0 (- (+ ly 16) (aref oam i)) (1- height)) collect i into found
                            and count t into count when (= count 10) return found finally (return found))))
        (when (or (not cgb) (= (ppu-opri ppu) 1))
          (setf sprites (stable-sort sprites #'< :key (lambda (i) (aref oam (1+ i))))))
        (dolist (i sprites)
          (let* ((left (- (aref oam (+ i 1)) 8)) (attr (aref oam (+ i 3)))
                 (row (- (+ ly 16) (aref oam i)))
                 (y (if (logbitp 6 attr) (- height 1 row) row))
                 (tile (logand (aref oam (+ i 2)) (if (= height 16) #xfe #xff)))
                 (address (+ (* tile 16) (* 2 y) (if (and cgb (logbitp 3 attr)) #x2000 0))))
            (dotimes (col 8)
              (let ((x (+ left col)))
                (when (and (<= 0 x 159) (zerop (aref (ppu-sprite-owned ppu) x)))
                  (let ((color (tile-pixel vram address (if (logbitp 5 attr) (- 7 col) col))))
                    (unless (zerop color)
                      (setf (aref (ppu-sprite-owned ppu) x) 1)
                      (unless (and (plusp (aref colors x))
                                   (if cgb (and (logbitp 0 lcdc) (or (logbitp 7 attr) (= 1 (aref (ppu-bg-priority ppu) x))))
                                       (logbitp 7 attr)))
                        (setf (aref frame (+ start x))
                              (if cgb (cgb-color (ppu-obj-palette ppu) (+ (* 4 (logand 7 attr)) color))
                                  (dmg-color (if (logbitp 4 attr) (ppu-obp1 ppu) (ppu-obp0 ppu)) color)))))))))))))))

(defun ppu-tick (ppu cycles vram oam &optional hblank-hook)
  "モード境界までまとめて進め、VBlank / STAT の要求ビットを返す。"
  (let ((interrupts 0))
    (when (logbitp 7 (ppu-lcdc ppu))
      (loop while (plusp cycles) do
        (let* ((boundary (case (ppu-mode ppu) (2 80) (3 252) (otherwise 456)))
               (step (min cycles (- boundary (ppu-dot ppu)))))
          (incf (ppu-dot ppu) step) (decf cycles step)
          (when (= boundary (ppu-dot ppu))
            (case boundary
              (80 (setf (ppu-mode ppu) 3))
              (252 (setf (ppu-mode ppu) 0) (ppu-render-line ppu vram oam)
                   (when hblank-hook (funcall hblank-hook)))
              (456
               (setf (ppu-dot ppu) 0 (ppu-ly ppu) (mod (1+ (ppu-ly ppu)) 154)
                     (ppu-lyc-equal ppu) (= (ppu-ly ppu) (ppu-lyc ppu))
                     (ppu-mode ppu) (if (>= (ppu-ly ppu) 144) 1 2))
               (when (zerop (ppu-ly ppu)) (setf (ppu-window-line ppu) 0))
               (when (= (ppu-ly ppu) 144) (setf interrupts (logior interrupts 1) (ppu-frame-ready ppu) t))))
            (when (ppu-stat-interrupt ppu) (setf interrupts (logior interrupts 2)))))))
    interrupts))
