(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(define-condition savestate-error (error)
  ((reason :initarg :reason :reader savestate-error-reason))
  (:report (lambda (condition stream)
             (format stream "セーブステートを読み込めません: ~A"
                     (case (savestate-error-reason condition)
                       (:magic "識別子が違います") (:version "未対応のバージョンです")
                       (:checksum "別の ROM のデータです") (:size "サイズが違います")
                       (otherwise "内部の状態値が不正です"))))))
(defstruct state-cursor buffer (position 10) reading)
(defun state-field (cursor value kind)
  (declare (optimize (safety 3)))
  (let* ((width (ecase kind (:u8 1) (:u16 2) (:u32 4) (:i64 8) (:bool 1)))
         (position (state-cursor-position cursor)) (buffer (state-cursor-buffer cursor)))
    (incf (state-cursor-position cursor) width)
    (cond ((null buffer) value)
          ((state-cursor-reading cursor)
           (let ((raw (loop for i below width sum (ash (aref buffer (+ position i)) (* 8 i)))))
             (case kind
               (:bool (unless (<= raw 1) (error 'savestate-error :reason :data)) (= raw 1))
               (:i64 (if (logbitp 63 raw) (- raw (ash 1 64)) raw))
               (otherwise raw))))
          (t (let ((raw (if (eq kind :bool) (if value 1 0) value)))
               (dotimes (i width) (setf (aref buffer (+ position i)) (ldb (byte 8 (* i 8)) raw)))) value))))

(defmacro define-state-codec (name &body fields)
  "スロットの宣言から、保存・復元・サイズ計算で共用する走査関数を生成する。"
  (let ((object (gensym "OBJECT")) (cursor (gensym "CURSOR")))
    `(defun ,(intern (format nil "STATE-~A" name)) (,object ,cursor)
       (declare (optimize (safety 3)))
       ,@(loop for (slot kind) in fields
               for accessor = (intern (format nil "~A-~A" name slot))
               collect
               (if (consp kind)
                   `(let ((array (,accessor ,object)))
                      (dotimes (i (length array))
                        (let ((value (state-field ,cursor (aref array i) ,(second kind))))
                          (when (state-cursor-reading ,cursor) (setf (aref array i) value)))))
                   `(let ((value (state-field ,cursor (,accessor ,object) ,kind)))
                      (when (state-cursor-reading ,cursor) (setf (,accessor ,object) value))))))))

(define-state-codec cpu
  (a :u8) (f :u8) (b :u8) (c :u8) (d :u8) (e :u8) (h :u8) (l :u8)
  (sp :u16) (pc :u16) (ime :bool) (ime-pending :i64) (halted :bool) (halt-bug :bool) (stopped :bool) (cycles :i64))
(define-state-codec bus
  (wram (:array :u8)) (vram (:array :u8)) (oam (:array :u8)) (hram (:array :u8)) (io (:array :u8))
  (ie :u8) (if :u8) (svbk :u8) (vbk :u8) (double-speed :bool) (speed-switch-prepared :bool)
  (hdma-source :u16) (hdma-destination :u16) (hdma-remaining :i64) (hdma-active :bool) (hdma-stall :i64)
  (dma-active :bool) (dma-source :u16) (dma-index :i64) (dma-delay :i64) (dma-clock :i64)
  (cycles :i64) (hw-cycles :i64))
(define-state-codec timer
  (div-counter :u16) (tima :u8) (tma :u8) (tac :u8) (overflow-delay :i64) (reloaded-p :bool))
(define-state-codec ppu
  (mode :u8) (dot :i64) (ly :u8) (lyc :u8) (lcdc :u8) (stat :u8) (scy :u8) (scx :u8)
  (wy :u8) (wx :u8) (bgp :u8) (obp0 :u8) (obp1 :u8) (window-line :i64) (stat-line :bool) (lyc-equal :bool)
  (bg-palette (:array :u8)) (obj-palette (:array :u8)) (bcps :u8) (ocps :u8) (opri :u8)
  (framebuffer (:array :u32)))
(define-state-codec apu
  (enabled :bool) (frame-step :i64) (frame-cycles :i64) (registers (:array :u8))
  (wave-access :i64) (wave-sample :u8) (sweep-shadow :i64) (sweep-timer :i64)
  (sweep-enabled :bool) (sweep-negated :bool) (sample-accumulator :i64) (sample-cycles :i64))
(define-state-codec audio-channel
  (enabled :bool) (dac :bool) (length :i64) (length-enabled :bool) (frequency :i64) (timer :i64)
  (position :i64) (volume :i64) (envelope-timer :i64) (lfsr :u16) (area :i64))
(define-state-codec cartridge
  (ram (:array :u8)) (rom-bank :u16) (ram-bank :u8) (bank-high :u8) (ram-enabled :bool) (banking-mode :u8)
  (rtc (:array :u8)) (latched-rtc (:array :u8)) (latch-prepared :bool) (rtc-base-unix :i64))
(define-state-codec joypad (selection :u8) (pressed :u8))

(defun walk-state (machine cursor)
  (declare (optimize (safety 3)))
  (let* ((bus (machine-bus machine)) (apu (bus-apu bus)))
    (state-cpu (machine-cpu machine) cursor)
    (state-bus bus cursor)
    (let ((cgb (state-field cursor (eq (bus-mode bus) :cgb) :bool))
          (frames (state-field cursor (machine-frame-count machine) :i64))
          (target (state-field cursor (machine-frame-target machine) :i64)))
      (when (state-cursor-reading cursor)
        (unless (eq cgb (eq (bus-mode bus) :cgb)) (error 'savestate-error :reason :data))
        (setf (machine-frame-count machine) frames (machine-frame-target machine) target)))
    (state-timer (bus-timer bus) cursor)
    (state-ppu (bus-ppu bus) cursor)
    (state-apu apu cursor)
    (loop for channel across (apu-channels apu) do (state-audio-channel channel cursor))
    (state-cartridge (bus-cart bus) cursor)
    (state-joypad (bus-joypad bus) cursor))
  (state-cursor-position cursor))
(defun savestate-size (machine) (walk-state machine (make-state-cursor)))
(defun save-state (machine)
  (let* ((size (savestate-size machine)) (buffer (make-array size :element-type 'u8 :initial-element 0))
         (rom (cartridge-rom (bus-cart (machine-bus machine)))))
    (replace buffer #(#x4c #x47 #x42 #x53 1 0 0 0))
    (setf (aref buffer 8) (aref rom #x14e) (aref buffer 9) (aref rom #x14f))
    (assert (= size (walk-state machine (make-state-cursor :buffer buffer))))
    buffer))
(defun validate-state-values (machine)
  (declare (optimize (safety 3)))
  (let* ((bus (machine-bus machine)) (cpu (machine-cpu machine)) (ppu (bus-ppu bus)) (apu (bus-apu bus))
         (timer (bus-timer bus)) (cart (bus-cart bus)))
    (unless (and (zerop (logand 15 (cpu-f cpu))) (<= 0 (cpu-ime-pending cpu) 2)
                 (<= 0 (cpu-cycles cpu))
                 (<= (timer-tac timer) 7) (<= 0 (timer-overflow-delay timer) 4)
                 (<= (bus-svbk bus) 7) (<= (bus-vbk bus) 1)
                 (<= 0 (bus-hdma-remaining bus) 128) (<= #x8000 (bus-hdma-destination bus) #x9ff0)
                 (zerop (logand 15 (bus-hdma-source bus)))
                 (zerop (logand 15 (bus-hdma-destination bus)))
                 (or (not (bus-hdma-active bus)) (plusp (bus-hdma-remaining bus)))
                 (<= 0 (bus-dma-index bus) 160) (<= 0 (bus-dma-delay bus) 2) (<= 0 (bus-dma-clock bus) 3)
                 (zerop (logand #xff (bus-dma-source bus)))
                 (or (not (bus-dma-active bus)) (< (bus-dma-index bus) 160))
                 (<= 0 (bus-hdma-stall bus)) (<= 0 (bus-cycles bus)) (<= 0 (bus-hw-cycles bus))
                 (<= 0 (machine-frame-count machine)) (<= 0 (machine-frame-target machine))
                 (<= (ppu-mode ppu) 3) (<= (ppu-ly ppu) 153) (<= 0 (ppu-dot ppu) 455)
                 (< (ppu-dot ppu) (case (ppu-mode ppu) (2 80) (3 252) (t 456)))
                 ;; 描画用の LY とドットが配列の範囲・モード境界を逸脱しない。
                 (if (logbitp 7 (ppu-lcdc ppu))
                     (case (ppu-mode ppu)
                       (1 (>= (ppu-ly ppu) 144))
                       (0 (and (< (ppu-ly ppu) 144) (>= (ppu-dot ppu) 252)))
                       (2 (< (ppu-ly ppu) 144))
                       (3 (and (< (ppu-ly ppu) 144) (>= (ppu-dot ppu) 80))))
                     (and (zerop (ppu-mode ppu)) (zerop (ppu-ly ppu)) (zerop (ppu-dot ppu))))
                 (zerop (logand #x87 (ppu-stat ppu)))
                 (zerop (logand #x40 (logior (ppu-bcps ppu) (ppu-ocps ppu))))
                 (<= 0 (ppu-window-line ppu) 144) (<= (ppu-opri ppu) 1)
                 (<= 0 (apu-frame-step apu) 7) (<= 0 (apu-frame-cycles apu) 8191)
                 (<= 0 (apu-sample-accumulator apu) 4194303) (<= 0 (apu-sample-cycles apu) 88)
                 (<= 0 (apu-wave-access apu) 2)
                 (<= 0 (apu-sweep-shadow apu) 2047) (<= 0 (apu-sweep-timer apu) 8)
                 (loop for ch across (apu-channels apu) for i from 0 always
                   (and (<= 0 (audio-channel-frequency ch) 2047)
                        (<= 0 (audio-channel-length ch) (if (= i 2) 256 64))
                        (<= 0 (audio-channel-position ch) (if (= i 2) 31 7))
                        (<= 0 (audio-channel-volume ch) 15)
                        (<= 0 (audio-channel-timer ch) (case i ((0 1) 8192) (2 4102) (3 3670016)))
                        (<= (audio-channel-lfsr ch) #x7fff)
                        (<= (abs (audio-channel-area ch)) (* 15 (apu-sample-cycles apu)))))
                 (<= (cartridge-bank-high cart) 3) (<= (cartridge-banking-mode cart) 1)
                 (case (cartridge-mbc-kind cart)
                   (:rom-only (= (cartridge-rom-bank cart) 1))
                   (:mbc1 (<= 1 (cartridge-rom-bank cart) 31))
                   (:mbc2 (and (<= 1 (cartridge-rom-bank cart) 15)
                               (every (lambda (v) (<= v 15)) (cartridge-ram cart))))
                   (:mbc3 (<= 1 (cartridge-rom-bank cart) 127))
                   (:mbc5 (and (<= (cartridge-rom-bank cart) 511) (<= (cartridge-ram-bank cart) 15))))
                 (loop for rtc in (list (cartridge-rtc cart) (cartridge-latched-rtc cart)) always
                   (and (< (aref rtc 0) 60) (< (aref rtc 1) 60) (< (aref rtc 2) 24)
                        (zerop (logand #x3e (aref rtc 4)))))
                 (<= 0 (cartridge-rtc-base-unix cart))
                 (zerop (logand #xcf (joypad-selection (bus-joypad bus)))))
      (error 'savestate-error :reason :data))))
(defun load-state (machine bytes)
  (declare (optimize (safety 3)))
  (let ((rom (cartridge-rom (bus-cart (machine-bus machine)))))
    (unless (and (typep bytes 'octets) (>= (length bytes) 4) (equalp (subseq bytes 0 4) #(#x4c #x47 #x42 #x53)))
      (error 'savestate-error :reason :magic))
    (unless (and (>= (length bytes) 8) (equalp (subseq bytes 4 8) #(1 0 0 0)))
      (error 'savestate-error :reason :version))
    (unless (and (>= (length bytes) 10) (= (aref bytes 8) (aref rom #x14e)) (= (aref bytes 9) (aref rom #x14f)))
      (error 'savestate-error :reason :checksum))
    (unless (= (length bytes) (savestate-size machine)) (error 'savestate-error :reason :size))
    ;; 別の状態へ復号して検証し、成功した場合だけ公開マシンへ入れ替える。
    (let ((restored (make-machine rom)))
      (handler-case
          (progn (walk-state restored (make-state-cursor :buffer bytes :reading t)) (validate-state-values restored))
        (error () (error 'savestate-error :reason :data)))
      (mbc-refresh-rom-windows (bus-cart (machine-bus restored)))
      (ppu-refresh-palettes (bus-ppu (machine-bus restored)))
      (setf (bus-serial-log (machine-bus restored)) (bus-serial-log (machine-bus machine))
            (cpu-debug-ld-b-b-hit (machine-cpu restored)) (cpu-debug-ld-b-b-hit (machine-cpu machine))
            (cartridge-ram-dirty (bus-cart (machine-bus restored))) t
            (machine-cpu machine) (machine-cpu restored) (machine-bus machine) (machine-bus restored)
            (machine-frame-count machine) (machine-frame-count restored)
            (machine-frame-target machine) (machine-frame-target restored)
            (machine-framebuffer machine) (machine-framebuffer restored))))
  machine)
