(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct timer
  (div-counter 0 :type u16) (tima 0 :type u8) (tma 0 :type u8) (tac 0 :type u8)
  (overflow-delay 0 :type fixnum) (reloaded-p nil :type boolean))
(declaim (inline timer-signal timer-increment))
(defun timer-signal (timer)
  (and (logbitp 2 (timer-tac timer))
       (logbitp (aref #(9 3 5 7) (logand 3 (timer-tac timer))) (timer-div-counter timer))))
(defun timer-increment (timer)
  (when (zerop (timer-overflow-delay timer))
    (if (= (timer-tima timer) #xff)
        (setf (timer-tima timer) 0 (timer-overflow-delay timer) 4)
        (incf (timer-tima timer)))))
(defun timer-tick (timer cycles)
  "立ち下がりと遅延再ロードの境界までまとめて進め、割り込み要求を返す。"
  (declare (type timer timer) (type fixnum cycles))
  (setf (timer-reloaded-p timer) nil)
  ;; タイマーが無効で再ロードもなければ、DIVだけを進める。
  (when (and (not (logbitp 2 (timer-tac timer))) (zerop (timer-overflow-delay timer)))
    (when (plusp cycles) (setf (timer-div-counter timer) (wrap16 (+ (timer-div-counter timer) cycles))))
    (return-from timer-tick nil))
  (let* ((interrupt nil) (enabled (logbitp 2 (timer-tac timer)))
         (period (ash 1 (1+ (aref #(9 3 5 7) (logand 3 (timer-tac timer))))))
         (mask (1- period)))
    (declare (type fixnum period mask))
    (loop while (plusp cycles) do
      (let* ((edge (if enabled (- period (logand (timer-div-counter timer) mask)) cycles))
             (delay (timer-overflow-delay timer))
             (step (min cycles edge (if (plusp delay) delay cycles))))
        (declare (type fixnum edge delay step))
        ;; 逐次更新と同じく、同時刻なら再ロードを先に、立ち下がりを後に処理する。
        (when (plusp delay)
          (when (zerop (decf (timer-overflow-delay timer) step))
            (setf (timer-tima timer) (timer-tma timer) (timer-reloaded-p timer) t interrupt t)))
        (setf (timer-div-counter timer) (wrap16 (+ (timer-div-counter timer) step)))
        (when (and enabled (= step edge)) (timer-increment timer))
        (decf cycles step)))
    interrupt))
(defun timer-read (timer address)
  (ecase address
    (#xff04 (ldb (byte 8 8) (timer-div-counter timer)))
    (#xff05 (timer-tima timer)) (#xff06 (timer-tma timer))
    (#xff07 (logior #xf8 (timer-tac timer)))))
(defun timer-write (timer address value)
  (ecase address
    (#xff04 (let ((old (timer-signal timer)))
              (setf (timer-div-counter timer) 0)
              (when old (timer-increment timer))))
    (#xff05 (unless (timer-reloaded-p timer)
              (setf (timer-overflow-delay timer) 0 (timer-tima timer) value)))
    (#xff06 (setf (timer-tma timer) value)
             (when (timer-reloaded-p timer) (setf (timer-tima timer) value)))
    (#xff07 (let ((old (timer-signal timer)))
              (setf (timer-tac timer) (logand 7 value))
              (when (and old (not (timer-signal timer))) (timer-increment timer))))))
