(in-package #:lispgb.core)
(declaim #.(core-optimize-spec))

(defstruct timer
  (div-counter 0 :type u16) (tima 0 :type u8) (tma 0 :type u8) (tac 0 :type u8)
  (overflow-delay 0 :type fixnum) (reloaded-p nil :type boolean))
(declaim (inline timer-signal timer-increment))
(defun timer-signal (timer)
  (and (logbitp 2 (timer-tac timer))
       (logbitp (aref #(9 3 5 7) (logand 3 (timer-tac timer))) (timer-div-counter timer))))
(defun timer-increment (timer)
  (when (zerop (timer-overflow-delay timer))
    (if (= (timer-tima timer) #xff)
        (setf (timer-tima timer) 0 (timer-overflow-delay timer) 4)
        (incf (timer-tima timer)))))
(defun timer-tick (timer cycles)
  "T サイクルごとに立ち下がりと再ロードを処理し、割り込み要求を返す。"
  (let ((interrupt nil))
    (setf (timer-reloaded-p timer) nil)
    (dotimes (i cycles)
      (when (plusp (timer-overflow-delay timer))
        (when (zerop (decf (timer-overflow-delay timer)))
          (setf (timer-tima timer) (timer-tma timer)
                (timer-reloaded-p timer) t interrupt t)))
      (let ((old (timer-signal timer)))
        (setf (timer-div-counter timer) (wrap16 (1+ (timer-div-counter timer))))
        (when (and old (not (timer-signal timer))) (timer-increment timer))))
    interrupt))
(defun timer-read (timer address)
  (ecase address
    (#xff04 (ldb (byte 8 8) (timer-div-counter timer)))
    (#xff05 (timer-tima timer)) (#xff06 (timer-tma timer))
    (#xff07 (logior #xf8 (timer-tac timer)))))
(defun timer-write (timer address value)
  (ecase address
    (#xff04 (let ((old (timer-signal timer)))
              (setf (timer-div-counter timer) 0)
              (when old (timer-increment timer))))
    (#xff05 (unless (timer-reloaded-p timer)
              (setf (timer-overflow-delay timer) 0 (timer-tima timer) value)))
    (#xff06 (setf (timer-tma timer) value)
             (when (timer-reloaded-p timer) (setf (timer-tima timer) value)))
    (#xff07 (let ((old (timer-signal timer)))
              (setf (timer-tac timer) (logand 7 value))
              (when (and old (not (timer-signal timer))) (timer-increment timer))))))
