;;; 通常ビルドで測定する。比較時は同じ ROM・フレーム数で複数回実行する。
(defun bench-count (name default &optional allow-zero)
  (let* ((text (uiop:getenv name)) (value (if text (parse-integer text) default)))
    (unless (if allow-zero (>= value 0) (> value 0)) (error "~A の値が不正です。" name))
    value))
(with-open-file (stream (uiop:getenv "LISPGB_BENCH_ROM") :element-type '(unsigned-byte 8))
  (let ((rom (make-array (file-length stream) :element-type '(unsigned-byte 8)))
        (frames (bench-count "LISPGB_BENCH_FRAMES" 3000))
        (repeats (bench-count "LISPGB_BENCH_REPEATS" 1))
        (warmup (bench-count "LISPGB_BENCH_WARMUP" 0 t)))
    (read-sequence rom stream)
    (dotimes (round repeats)
      (let ((machine (lispgb.core:make-machine rom)))
        (dotimes (i warmup) (lispgb.core:run-frame machine))
        (sb-ext:gc :full t)
        (let ((start (get-internal-real-time)) (cpu (get-internal-run-time))
              (bytes (sb-ext:get-bytes-consed)))
          (dotimes (i frames) (lispgb.core:run-frame machine))
          (let ((seconds (/ (- (get-internal-real-time) start) (float internal-time-units-per-second)))
                (cpu-seconds (/ (- (get-internal-run-time) cpu) (float internal-time-units-per-second))))
            (format t "~D 回目: ~D フレーム、実時間 ~,4F 秒、CPU ~,4F 秒、~,2F fps、割当 ~D バイト~%"
                    (1+ round) frames seconds cpu-seconds (/ frames seconds)
                    (- (sb-ext:get-bytes-consed) bytes))))))))
