(in-package #:lispgb.tests)
(deftest apu-power-and-wave-ram ()
  (let ((apu (lispgb.core::make-apu)))
    (lispgb.core::apu-write apu #xff26 #x80)
    (lispgb.core::apu-write apu #xff24 #x77)
    (lispgb.core::apu-write apu #xff30 #xab)
    (lispgb.core::apu-write apu #xff26 0)
    (is (= 0 (lispgb.core::apu-read apu #xff24)))
    (is (= #x70 (lispgb.core::apu-read apu #xff26)))
    (is (= #xab (lispgb.core::apu-read apu #xff30)))))
(deftest apu-length ()
  (let ((apu (lispgb.core::make-apu)))
    (lispgb.core::apu-write apu #xff26 #x80)
    (lispgb.core::apu-write apu #xff11 #x3f)
    (lispgb.core::apu-write apu #xff12 #xf0)
    (lispgb.core::apu-write apu #xff14 #xc0)
    (is (logbitp 0 (lispgb.core::apu-read apu #xff26)))
    (lispgb.core::apu-tick apu 8192)
    (is (not (logbitp 0 (lispgb.core::apu-read apu #xff26))))))
(deftest apu-envelope-and-sweep ()
  (let ((apu (lispgb.core::make-apu)))
    (lispgb.core::apu-write apu #xff26 #x80)
    (lispgb.core::apu-write apu #xff17 #x21)
    (lispgb.core::apu-write apu #xff19 #x80)
    (lispgb.core::apu-tick apu 65536)
    (is (= 1 (lispgb.core::audio-channel-volume (aref (lispgb.core::apu-channels apu) 1))))
    (lispgb.core::apu-write apu #xff10 #x11)
    (lispgb.core::apu-write apu #xff12 #xf0)
    (lispgb.core::apu-write apu #xff13 #xff)
    (lispgb.core::apu-write apu #xff14 #x87)
    (is (not (logbitp 0 (lispgb.core::apu-read apu #xff26))))))
(deftest apu-sample-rate ()
  (let ((apu (lispgb.core::make-apu)) (buffer (make-array 2048 :element-type '(signed-byte 16))))
    (lispgb.core::apu-tick apu 70224)
    (is (= (* 2 (floor (* 70224 48000) 4194304)) (lispgb.core::apu-drain apu buffer)))
    (is (= 0 (lispgb.core::apu-drain apu buffer)))
    (is (every #'zerop buffer))))

(deftest apu-wave-access-window ()
  (let ((apu (lispgb.core::make-apu)))
    (lispgb.core::apu-write apu #xff26 #x80)
    (lispgb.core::apu-write apu #xff30 #xab)
    (lispgb.core::apu-write apu #xff31 #xcd)
    (lispgb.core::apu-write apu #xff1a #x80)
    (lispgb.core::apu-write apu #xff1d #xfe)
    (lispgb.core::apu-write apu #xff1e #x87)
    (is (= #xff (lispgb.core::apu-read apu #xff30)))
    (lispgb.core::apu-tick apu 10)
    (is (= #xab (lispgb.core::apu-read apu #xff3f)))
    (lispgb.core::apu-tick apu 2)
    (is (= #xff (lispgb.core::apu-read apu #xff30)))
    (lispgb.core::apu-write apu #xff30 #xee)
    (lispgb.core::apu-write apu #xff1a 0)
    (is (= #xab (lispgb.core::apu-read apu #xff30)))))

(deftest apu-power-clears-length-enable ()
  (let ((apu (lispgb.core::make-apu)))
    (lispgb.core::apu-write apu #xff26 #x80)
    (lispgb.core::apu-write apu #xff23 #x40)
    (lispgb.core::apu-write apu #xff26 0)
    (lispgb.core::apu-write apu #xff20 #x2e)
    (lispgb.core::apu-write apu #xff26 #x80)
    (lispgb.core::apu-tick apu 65536)
    (is (= 18 (lispgb.core::audio-channel-length (aref (lispgb.core::apu-channels apu) 3))))))
