(in-package #:lispgb.tests)
(defun little-endian-at (bytes offset width)
  (loop for i below width sum (ash (aref bytes (+ offset i)) (* 8 i))))
(deftest bmp-header-and-pixels ()
  (let ((path (asdf:system-relative-pathname "lispgb" "build/test-image.bmp")))
    (unwind-protect
        (progn
          (lispgb::write-bmp path #( #xffff0000 #xff00ff00 #xff0000ff #xffffffff) 2 2)
          (let ((bytes (lispgb::read-file-octets path)))
            (is (= 70 (length bytes)))
            (is (equalp #(66 77) (subseq bytes 0 2)))
            (is (= 70 (little-endian-at bytes 2 4)))
            (is (= 54 (little-endian-at bytes 10 4)))
            (is (= 40 (little-endian-at bytes 14 4)))
            (is (= 2 (little-endian-at bytes 18 4)))
            (is (= 2 (little-endian-at bytes 22 4)))
            (is (= 1 (little-endian-at bytes 26 2)))
            (is (= 24 (little-endian-at bytes 28 2)))
            (is (= 0 (little-endian-at bytes 30 4)))
            (is (equalp #(255 0 0 255 255 255 0 0 0 0 255 0 255 0 0 0) (subseq bytes 54)))))
      (when (probe-file path) (delete-file path)))))
