(in-package #:lispgb.tests)
(deftest bus-memory-map ()
  (let ((bus (lispgb.core::make-bus :mode :cgb)))
    (lispgb.core::bus-write bus #xc123 #x42)
    (is (= #x42 (lispgb.core::bus-read bus #xe123)))
    (lispgb.core::bus-write bus #xf123 #x77)
    (is (= #x77 (lispgb.core::bus-read bus #xd123)))
    (lispgb.core::bus-write bus #xff70 2)
    (is (zerop (lispgb.core::bus-read bus #xd123)))
    (lispgb.core::bus-write bus #xff70 0)
    (is (= #x77 (lispgb.core::bus-read bus #xd123)))
    (lispgb.core::bus-write bus #x8000 12)
    (lispgb.core::bus-write bus #xff4f 1)
    (is (zerop (lispgb.core::bus-read bus #x8000)))
    (lispgb.core::bus-write bus #x8000 34)
    (lispgb.core::bus-write bus #xff4f 0)
    (is (= 12 (lispgb.core::bus-read bus #x8000)))
    (lispgb.core::bus-write bus #xfea0 42)
    (is (= #xff (lispgb.core::bus-read bus #xfea0)))))
(deftest bus-serial ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff01 65)
    (lispgb.core::bus-write bus #xff02 #x81)
    (is (equalp #(65) (lispgb.core::bus-serial-log bus)))))

(deftest bus-oam-dma ()
  (let ((bus (lispgb.core::make-bus)))
    (dotimes (i 160) (lispgb.core::bus-write bus (+ #xc000 i) (logand i 255)))
    (lispgb.core::bus-write bus #xff46 #xc0)
    (lispgb.core::bus-tick bus 4)
    (lispgb.core::bus-tick bus 4)
    (is (= #xff (lispgb.core::bus-read bus #xfe00)))
    (lispgb.core::bus-tick bus 636)
    (dotimes (i 160) (is (= i (lispgb.core::bus-read bus (+ #xfe00 i)))))))

(deftest dma-idle-clock-and-restart ()
  (let ((bus (lispgb.core::make-bus)))
    (dolist (cycles '(0 1 2 3 4 7 8 255 1024))
      (let ((before (lispgb.core::bus-dma-clock bus)))
        (lispgb.core::bus-tick bus cycles)
        (is (= (mod (+ before cycles) 4) (lispgb.core::bus-dma-clock bus)))))
    (lispgb.core::bus-write bus #xc000 #x42)
    (lispgb.core::bus-write bus #xff46 #xc0)
    (lispgb.core::bus-tick bus 7)
    (is (not (lispgb.core::bus-dma-active bus)))
    (lispgb.core::bus-tick bus 1)
    (is (lispgb.core::bus-dma-active bus))
    (is (= #x42 (aref (lispgb.core::bus-oam bus) 0)))
    (lispgb.core::bus-tick bus (* 159 4))
    (is (not (lispgb.core::bus-dma-active bus)))))
