(in-package #:lispgb.tests)
(deftest bus-memory-map ()
  (let ((bus (lispgb.core::make-bus :mode :cgb)))
    (lispgb.core::bus-write bus #xc123 #x42)
    (is (= #x42 (lispgb.core::bus-read bus #xe123)))
    (lispgb.core::bus-write bus #xf123 #x77)
    (is (= #x77 (lispgb.core::bus-read bus #xd123)))
    (lispgb.core::bus-write bus #xff70 2)
    (is (zerop (lispgb.core::bus-read bus #xd123)))
    (lispgb.core::bus-write bus #xff70 0)
    (is (= #x77 (lispgb.core::bus-read bus #xd123)))
    (lispgb.core::bus-write bus #x8000 12)
    (lispgb.core::bus-write bus #xff4f 1)
    (is (zerop (lispgb.core::bus-read bus #x8000)))
    (lispgb.core::bus-write bus #x8000 34)
    (lispgb.core::bus-write bus #xff4f 0)
    (is (= 12 (lispgb.core::bus-read bus #x8000)))
    (lispgb.core::bus-write bus #xfea0 42)
    (is (= #xff (lispgb.core::bus-read bus #xfea0)))))
(deftest bus-serial ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff01 65)
    (lispgb.core::bus-write bus #xff02 #x81)
    (is (equalp #(65) (lispgb.core::bus-serial-log bus)))))
