(in-package #:lispgb.tests)

(deftest cgb-speed-switch ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom :cgb #x80)))
         (bus (lispgb.core::machine-bus machine)) (cpu (lispgb.core::machine-cpu machine)))
    (setf (aref (lispgb.core::bus-rom bus) #x100) #x10)
    (lispgb.core::bus-write bus #xff4d 1)
    (is (= #x7f (lispgb.core::bus-read bus #xff4d)))
    (lispgb.core::cpu-step cpu bus)
    (is (= #xfe (lispgb.core::bus-read bus #xff4d)))
    (is (not (lispgb.core::cpu-stopped cpu)))
    (let ((before (lispgb.core::bus-hw-cycles bus)))
      (lispgb.core::bus-tick bus 4)
      (is (= 2 (- (lispgb.core::bus-hw-cycles bus) before))))))

(deftest cgb-palette-and-attributes ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom :cgb #x80)))
         (bus (lispgb.core::machine-bus machine)))
    (lispgb.core::bus-write bus #xff68 #x8a)
    (lispgb.core::bus-write bus #xff69 #x1f)
    (lispgb.core::bus-write bus #xff69 0)
    (is (= #xcc (lispgb.core::bus-read bus #xff68)))
    (lispgb.core::bus-write bus #xff6a #xbf)
    (lispgb.core::bus-write bus #xff6b #x12)
    (is (= #xc0 (lispgb.core::bus-read bus #xff6a)))
    (lispgb.core::bus-write bus #xff4f 1)
    (lispgb.core::bus-write bus #x9800 #x6a)
    (lispgb.core::bus-write bus #x800e 1)
    (lispgb.core::bus-write bus #xff4f 0)
    (lispgb.core::bus-tick bus 252)
    (is (= #xffff0000 (aref (lispgb.core:machine-framebuffer machine) 0)))))

(defun prepare-cgb-dma (bus)
  (dotimes (i 32) (lispgb.core::bus-write bus (+ #xc120 i) (1+ i)))
  (lispgb.core::bus-write bus #xff51 #xc1)
  (lispgb.core::bus-write bus #xff52 #x23)
  (lispgb.core::bus-write bus #xff53 #x1f)
  (lispgb.core::bus-write bus #xff54 #xe7))
(deftest cgb-gdma ()
  (let ((bus (lispgb.core::make-bus :mode :cgb)))
    (prepare-cgb-dma bus)
    (lispgb.core::bus-write bus #xff55 1)
    (dotimes (i 32) (is (= (1+ i) (lispgb.core::bus-read bus (+ #x9fe0 i)))))
    (is (= #xff (lispgb.core::bus-read bus #xff55)))))
(deftest cgb-hdma ()
  (let ((bus (lispgb.core::make-bus :mode :cgb)))
    (prepare-cgb-dma bus)
    (lispgb.core::bus-write bus #xff40 #x91)
    (lispgb.core::bus-write bus #xff55 #x81)
    (lispgb.core::bus-tick bus 252)
    (is (= 1 (lispgb.core::bus-read bus #x9fe0)))
    (is (= 0 (lispgb.core::bus-read bus #x9ff0)))
    (is (= 0 (lispgb.core::bus-read bus #xff55)))
    (lispgb.core::bus-tick bus 456)
    (is (= 17 (lispgb.core::bus-read bus #x9ff0)))
    (is (= #xff (lispgb.core::bus-read bus #xff55)))))
(deftest cgb-dmg-compatibility ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom)))
         (bus (lispgb.core::machine-bus machine)))
    (is (eq :dmg (lispgb.core::bus-mode bus)))
    (lispgb.core::bus-write bus #xff4d 1)
    (lispgb.core::bus-write bus #xff68 #x80)
    (is (= #xff (lispgb.core::bus-read bus #xff4d)))
    (is (= #xff (lispgb.core::bus-read bus #xff68)))))

(dolist (name '(cgb-speed-switch cgb-palette-and-attributes cgb-gdma cgb-hdma cgb-dmg-compatibility))
  (register-pending name "T034"))
