(in-package #:lispgb.tests)
(deftest cli-all-options ()
  (let ((o (lispgb::parse-args '("--scale" "9" "--fullscreen" "--shader" "smooth" "--headless" "--frames" "120" "--screenshot" "out.bmp" "rom.gbc"))))
    (is (= 8 (lispgb::cli-options-scale o)))
    (is (lispgb::cli-options-fullscreen o))
    (is (eq :smooth (lispgb::cli-options-shader o)))
    (is (= 120 (lispgb::cli-options-frames o)))
    (is (string= "out.bmp" (lispgb::cli-options-screenshot o)))
    (is (string= "rom.gbc" (lispgb::cli-options-rom o))))
  (is (lispgb::cli-options-recent (lispgb::parse-args '("--recent"))))
  (is (lispgb::cli-options-help (lispgb::parse-args '("--help"))))
  (is (lispgb::cli-options-version (lispgb::parse-args '("-v")))))
(deftest cli-errors ()
  (dolist (args '(("--scale" "0" "x") ("--scale" "abc" "x") ("--scale") ("--wat") ()
                  ("--headless" "x") ("--frames" "0" "--headless" "x") ("--frames" "2" "x")
                  ("--shader" "blur" "x") ("x" "y") ("--screenshot")))
    (is (signals-condition-p 'lispgb::usage-error (lambda () (lispgb::parse-args args))))))
(register-pending 'cli-all-options "T060")
