(in-package #:lispgb.tests)
(deftest config-parse ()
  (let ((config (lispgb::parse-config-text (format nil "# 設定~% scale = 9 # 拡大~% fullscreen = true~%shader=smooth~%volume = 25~%unknown=1~%"))))
    (is (= 8 (lispgb::app-config-scale config)))
    (is (lispgb::app-config-fullscreen config))
    (is (eq :smooth (lispgb::app-config-shader config)))
    (is (= 25 (lispgb::app-config-volume config))))
  (let ((config (lispgb::parse-config-text (format nil "scale=0~%fullscreen=maybe~%shader=other~%volume=101~%bad line~%"))))
    (is (= 4 (lispgb::app-config-scale config)))
    (is (not (lispgb::app-config-fullscreen config)))
    (is (eq :nearest (lispgb::app-config-shader config)))
    (is (= 100 (lispgb::app-config-volume config)))))
(deftest config-location ()
  (is (equal #P"/tmp/config/LispGB/" (lispgb::config-directory "/tmp/config" #P"/tmp/home/")))
  (is (equal #P"/tmp/home/.config/LispGB/" (lispgb::config-directory "" #P"/tmp/home/"))))
(deftest config-generate-defaults ()
  (let* ((directory (asdf:system-relative-pathname "lispgb" "build/test-config/"))
         (path (merge-pathnames "config.txt" directory)))
    (unwind-protect
        (let ((config (lispgb::load-config directory)))
          (is (probe-file path))
          (is (= 4 (lispgb::app-config-scale config)))
          (is (search "volume = 100" (uiop:read-file-string path))))
      (when (probe-file path) (delete-file path)))))
(deftest recent-order-and-limit ()
  (let* ((old (loop for i below 12 collect (format nil "/tmp/rom~D.gb" i)))
         (next (lispgb::update-recent-list "/tmp/rom5.gb" old)))
    (is (= 10 (length next)))
    (is (string= "/tmp/rom5.gb" (first next)))
    (is (= 1 (count "/tmp/rom5.gb" next :test #'string=)))
    (is (string= "/tmp/rom0.gb" (second next)))))


(deftest config-cli-precedence ()
  (let* ((base (lispgb::parse-config-text (format nil "scale=2~%shader=smooth~%volume=25~%")))
         (result (lispgb::apply-cli-config base (lispgb::parse-args '("--scale" "3" "game.gb")))))
    (is (= 3 (lispgb::app-config-scale result)))
    (is (eq :smooth (lispgb::app-config-shader result)))
    (is (= 25 (lispgb::app-config-volume result)))
    (is (= 2 (lispgb::app-config-scale base)))))

(deftest recent-file-roundtrip ()
  (let* ((directory (asdf:system-relative-pathname "lispgb" "build/test-config/"))
         (path (merge-pathnames "recent.txt" directory))
         (rom (asdf:system-relative-pathname "lispgb" "lispgb.asd")))
    (ensure-directories-exist path)
    (unwind-protect
        (progn
          (lispgb::remember-rom directory rom)
          (lispgb::remember-rom directory rom)
          (is (equal (list (namestring (truename rom))) (lispgb::read-recent directory))))
      (when (probe-file path) (delete-file path)))))
