(in-package #:lispgb.tests)
(deftest config-parse ()
  (let ((config (lispgb::parse-config-text (format nil "# 設定~% scale = 9 # 拡大~% fullscreen = true~%shader=smooth~%volume = 25~%unknown=1~%"))))
    (is (= 8 (lispgb::app-config-scale config)))
    (is (lispgb::app-config-fullscreen config))
    (is (eq :smooth (lispgb::app-config-shader config)))
    (is (= 25 (lispgb::app-config-volume config))))
  (let ((config (lispgb::parse-config-text (format nil "scale=0~%fullscreen=maybe~%shader=other~%volume=101~%bad line~%"))))
    (is (= 4 (lispgb::app-config-scale config)))
    (is (not (lispgb::app-config-fullscreen config)))
    (is (eq :nearest (lispgb::app-config-shader config)))
    (is (= 100 (lispgb::app-config-volume config)))))
(deftest config-location ()
  (is (equal #P"/tmp/config/LispGB/" (lispgb::config-directory "/tmp/config" #P"/tmp/home/" :linux)))
  (is (equal #P"/tmp/home/.config/LispGB/" (lispgb::config-directory "" #P"/tmp/home/" :linux))))
(deftest config-generate-defaults ()
  (let* ((directory (asdf:system-relative-pathname "lispgb" "build/test-config/"))
         (path (merge-pathnames "config.txt" directory)))
    (unwind-protect
        (let ((config (lispgb::load-config directory)))
          (is (probe-file path))
          (is (= 4 (lispgb::app-config-scale config)))
          (is (search "volume = 100" (uiop:read-file-string path))))
      (when (probe-file path) (delete-file path)))))
(deftest recent-order-and-limit ()
  (let* ((old (loop for i below 12 collect (format nil "/tmp/rom~D.gb" i)))
         (next (lispgb::update-recent-list "/tmp/rom5.gb" old)))
    (is (= 10 (length next)))
    (is (string= "/tmp/rom5.gb" (first next)))
    (is (= 1 (count "/tmp/rom5.gb" next :test #'string=)))
    (is (string= "/tmp/rom0.gb" (second next)))))


(deftest config-cli-precedence ()
  (let* ((base (lispgb::parse-config-text (format nil "scale=2~%shader=smooth~%volume=25~%")))
         (result (lispgb::apply-cli-config base (lispgb::parse-args '("--scale" "3" "game.gb")))))
    (is (= 3 (lispgb::app-config-scale result)))
    (is (eq :smooth (lispgb::app-config-shader result)))
    (is (= 25 (lispgb::app-config-volume result)))
    (is (= 2 (lispgb::app-config-scale base)))))

(deftest recent-file-roundtrip ()
  (let* ((directory (asdf:system-relative-pathname "lispgb" "build/test-config/"))
         (path (merge-pathnames "recent.txt" directory))
         (rom (asdf:system-relative-pathname "lispgb" "lispgb.asd")))
    (ensure-directories-exist path)
    (unwind-protect
        (progn
          (lispgb::remember-rom directory rom)
          (lispgb::remember-rom directory rom)
          (is (equal (list (namestring (truename rom))) (lispgb::read-recent directory))))
      (when (probe-file path) (delete-file path)))))

(deftest audio-volume ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom)))
         (apu (lispgb.core::bus-apu (lispgb.core::machine-bus machine)))
         (audio (lispgb::make-audio)))
    (setf (aref (lispgb.core::apu-ring apu) 0) 1000 (aref (lispgb.core::apu-ring apu) 1) -1000
          (lispgb.core::apu-ring-count apu) 1)
    (lispgb::output-audio audio machine 25)
    (is (= 250 (aref (lispgb::audio-buffer audio) 0)))
    (is (= -250 (aref (lispgb::audio-buffer audio) 1)))))

(deftest config-location-macos ()
  ;; macOS は XDG_CONFIG_HOME に依存せず、ホーム以下の標準保存先を使う。
  (dolist (xdg (list nil "" "/tmp/xdg/"))
    (is (equal #P"/tmp/home/Library/Application Support/LispGB/"
               (lispgb::config-directory xdg #P"/tmp/home/" :macos)))))

(deftest atomic-save-relative-path ()
  ;; rename-file の相対宛先は元ファイルのディレクトリに対して解決される。
  (let* ((root (asdf:system-source-directory "lispgb"))
         (relative #P"build/test-relative-save/state.bin")
         (absolute (merge-pathnames relative root))
         (bytes (make-array 3 :element-type '(unsigned-byte 8) :initial-contents '(1 2 3))))
    (ensure-directories-exist absolute)
    (unwind-protect
        (uiop:with-current-directory (root)
          (lispgb::write-file-atomically relative bytes)
          (is (equalp bytes (lispgb::read-file-octets absolute)))
          (lispgb::write-file-atomically relative (reverse bytes))
          (is (equalp (reverse bytes) (lispgb::read-file-octets absolute))))
      (when (probe-file absolute) (delete-file absolute)))))

(deftest save-ram-relative-backup ()
  (let* ((root (asdf:system-source-directory "lispgb"))
         (rom-path #P"build/test-relative-save/game.gb")
         (save (merge-pathnames (lispgb::save-ram-path rom-path) root))
         (backup (pathname (concatenate 'string (namestring save) ".bak")))
         (machine (lispgb.core:make-machine (synthetic-rom :type #x03 :ram-code 2))))
    (ensure-directories-exist save)
    (unwind-protect
        (uiop:with-current-directory (root)
          (lispgb::write-file-atomically save (make-array 1 :element-type '(unsigned-byte 8) :initial-element 42))
          (let ((persistence (lispgb::open-persistence machine rom-path)))
            (is (probe-file backup))
            (is (= 42 (aref (lispgb::read-file-octets backup) 0)))
            (lispgb::flush-save-ram persistence machine)
            (is (= 8192 (length (lispgb::read-file-octets save))))))
      (when (probe-file save) (delete-file save))
      (when (probe-file backup) (delete-file backup)))))
