(in-package #:lispgb.tests)

(defun cpu-fixture (&rest bytes)
  (let ((bus (lispgb.core::make-bus)) (cpu (lispgb.core::make-cpu)))
    (replace (lispgb.core::bus-rom bus) bytes :start1 #x100)
    (values cpu bus)))

(deftest cpu-arithmetic ()
  (dolist (row '((#xc6 #xff 1 0 0 #xb0) (#xce #x0f 0 #x10 #x10 #x20)
                 (#xd6 0 1 0 #xff #x70) (#xde #x10 #x0f #x10 0 #xe0)
                 (#xe6 #xff 0 0 0 #xa0) (#xee #xaa #xaa 0 0 #x80)
                 (#xf6 0 1 0 1 0) (#xfe 1 1 0 1 #xc0)))
    (destructuring-bind (opcode a value flags result expected-flags) row
      (multiple-value-bind (cpu bus) (cpu-fixture opcode value)
        (setf (lispgb.core::cpu-a cpu) a (lispgb.core::cpu-f cpu) flags)
        (is (= 8 (lispgb.core::cpu-step cpu bus)))
        (is (= result (lispgb.core::cpu-a cpu)))
        (is (= expected-flags (lispgb.core::cpu-f cpu)))))))

(deftest cpu-inc-dec-daa ()
  (multiple-value-bind (cpu bus) (cpu-fixture #x3c #x3d #x27)
    (setf (lispgb.core::cpu-a cpu) #xff (lispgb.core::cpu-f cpu) #x10)
    (lispgb.core::cpu-step cpu bus)
    (is (= #xb0 (lispgb.core::cpu-f cpu)))
    (lispgb.core::cpu-step cpu bus)
    (is (= #xff (lispgb.core::cpu-a cpu)))
    (is (= #x70 (lispgb.core::cpu-f cpu)))
    (setf (lispgb.core::cpu-a cpu) #x9a (lispgb.core::cpu-f cpu) 0)
    (lispgb.core::cpu-step cpu bus)
    (is (= 0 (lispgb.core::cpu-a cpu)))
    (is (= #x90 (lispgb.core::cpu-f cpu)))))

(deftest cpu-pairs-stack ()
  (multiple-value-bind (cpu bus) (cpu-fixture #x09 #xe8 #xff #xf5 #xf1)
    (setf (lispgb.core::cpu-h cpu) #x0f (lispgb.core::cpu-l cpu) #xff
          (lispgb.core::cpu-b cpu) 0 (lispgb.core::cpu-c cpu) 1)
    (is (= 8 (lispgb.core::cpu-step cpu bus)))
    (is (= #x10 (lispgb.core::cpu-h cpu)))
    (is (= #x20 (logand #x70 (lispgb.core::cpu-f cpu))))
    (setf (lispgb.core::cpu-sp cpu) #xd001)
    (is (= 16 (lispgb.core::cpu-step cpu bus)))
    (is (= #xd000 (lispgb.core::cpu-sp cpu)))
    (is (= #x30 (lispgb.core::cpu-f cpu)))
    (setf (lispgb.core::cpu-f cpu) #xff)
    (is (= 16 (lispgb.core::cpu-step cpu bus)))
    (is (= #xf0 (lispgb.core::bus-read bus #xcffe)))
    (lispgb.core::bus-write bus #xcffe #xff)
    (is (= 12 (lispgb.core::cpu-step cpu bus)))
    (is (= #xf0 (lispgb.core::cpu-f cpu)))))

(deftest cpu-rotates-cb ()
  (loop for opcode in '(0 1 2 3 4 5 6 7)
        for expected in '(3 #xc0 3 #xc0 2 #xc0 #x18 #x40)
        do (multiple-value-bind (cpu bus) (cpu-fixture #xcb (* opcode 8))
             (setf (lispgb.core::cpu-b cpu) #x81 (lispgb.core::cpu-f cpu) #x10)
             (is (= 8 (lispgb.core::cpu-step cpu bus)))
             (is (= expected (lispgb.core::cpu-b cpu)))
             (is (= (if (= opcode 6) 0 #x10) (lispgb.core::cpu-f cpu)))))
  (multiple-value-bind (cpu bus) (cpu-fixture #xcb #x46 #xcb #xc6 #xcb #x86 #x07)
    (setf (lispgb.core::cpu-h cpu) #xc0 (lispgb.core::cpu-l cpu) 0)
    (is (= 12 (lispgb.core::cpu-step cpu bus)))
    (is (logbitp 7 (lispgb.core::cpu-f cpu)))
    (is (= 16 (lispgb.core::cpu-step cpu bus)))
    (is (= 1 (lispgb.core::bus-read bus #xc000)))
    (is (= 16 (lispgb.core::cpu-step cpu bus)))
    (is (= 0 (lispgb.core::bus-read bus #xc000)))
    (setf (lispgb.core::cpu-a cpu) 0)
    (lispgb.core::cpu-step cpu bus)
    (is (= 0 (lispgb.core::cpu-f cpu)))))

(deftest cpu-branch-cycles ()
  (dolist (row '((#x20 8 12) (#xc2 12 16) (#xc4 12 24) (#xc0 8 20)))
    (destructuring-bind (opcode untaken taken) row
      (dolist (zero '(t nil))
        (multiple-value-bind (cpu bus) (cpu-fixture opcode 0 1)
          (setf (lispgb.core::cpu-f cpu) (if zero #x80 0))
          (is (= (if zero untaken taken) (lispgb.core::cpu-step cpu bus))))))))

(deftest cpu-interrupt-halt ()
  (multiple-value-bind (cpu bus) (cpu-fixture #xfb #x00 #x00)
    (setf (lispgb.core::bus-ie bus) 5 (lispgb.core::bus-if bus) 5)
    (is (= 4 (lispgb.core::cpu-step cpu bus)))
    (is (= 4 (lispgb.core::cpu-step cpu bus)))
    (is (= 20 (lispgb.core::cpu-step cpu bus)))
    (is (= #x40 (lispgb.core::cpu-pc cpu)))
    (is (= 4 (lispgb.core::bus-if bus))))
  (multiple-value-bind (cpu bus) (cpu-fixture #x76 #x3e #x12)
    (setf (lispgb.core::bus-ie bus) 1 (lispgb.core::bus-if bus) 1)
    (lispgb.core::cpu-step cpu bus)
    (lispgb.core::cpu-step cpu bus)
    (is (= #x3e (lispgb.core::cpu-a cpu)))))
(dolist (name '(cpu-arithmetic cpu-inc-dec-daa cpu-pairs-stack cpu-rotates-cb cpu-branch-cycles cpu-interrupt-halt))
  (register-pending name "T016"))
