(in-package #:lispgb.tests)
(deftest joypad-selection-and-edge ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom)))
         (bus (lispgb.core::machine-bus machine)))
    (lispgb.core::bus-write bus #xff00 #x30)
    (lispgb.core:set-buttons machine '(:right :b))
    (is (= #xff (lispgb.core::bus-read bus #xff00)))
    (setf (lispgb.core::bus-if bus) 0)
    (lispgb.core::bus-write bus #xff00 #x20)
    (is (= #xee (lispgb.core::bus-read bus #xff00)))
    (is (logbitp 4 (lispgb.core::bus-if bus)))
    (setf (lispgb.core::bus-if bus) 0)
    (lispgb.core:set-buttons machine '(:right :b))
    (is (= 0 (lispgb.core::bus-if bus)))
    (lispgb.core::bus-write bus #xff00 #x10)
    (is (= #xdd (lispgb.core::bus-read bus #xff00)))
    (lispgb.core::bus-write bus #xff00 0)
    (is (= #xcc (lispgb.core::bus-read bus #xff00)))
    (setf (lispgb.core::bus-if bus) 0)
    (lispgb.core:set-buttons machine nil)
    (is (= #xcf (lispgb.core::bus-read bus #xff00)))
    (is (= 0 (lispgb.core::bus-if bus)))
    (lispgb.core:set-buttons machine '(:start))
    (is (logbitp 4 (lispgb.core::bus-if bus)))))
(register-pending 'joypad-selection-and-edge "T037")
