(in-package #:lispgb.tests)
(defun banked-rom (type code ram)
  (let ((rom (synthetic-rom :type type :rom-code code :ram-code ram)))
    (loop for bank below (ash 2 code) do
      (setf (aref rom (* bank #x4000)) (logand bank #xff)
            (aref rom (1+ (* bank #x4000))) (ash bank -8)))
    rom))
(deftest mbc1-banks ()
  (let ((cart (lispgb.core::make-cartridge (banked-rom 3 5 3))))
    (is (= 1 (lispgb.core::mbc-read cart #x4000)))
    (lispgb.core::mbc-write cart #x2000 0)
    (is (= 1 (lispgb.core::mbc-read cart #x4000)))
    (lispgb.core::mbc-write cart #x4000 1)
    (is (= 33 (lispgb.core::mbc-read cart #x4000)))
    (is (= 0 (lispgb.core::mbc-read cart 0)))
    (lispgb.core::mbc-write cart #x6000 1)
    (is (= 32 (lispgb.core::mbc-read cart 0)))
    (is (= #xff (lispgb.core::mbc-read cart #xa000)))
    (lispgb.core::mbc-write cart 0 #x0a)
    (lispgb.core::mbc-write cart #xa000 #x42)
    (lispgb.core::mbc-write cart #x4000 2)
    (is (= 0 (lispgb.core::mbc-read cart #xa000)))
    (lispgb.core::mbc-write cart #x4000 1)
    (is (= #x42 (lispgb.core::mbc-read cart #xa000)))
    (is (lispgb.core::cartridge-ram-dirty cart))))
(deftest mbc2-nibbles ()
  (let ((cart (lispgb.core::make-cartridge (banked-rom 6 2 0))))
    (lispgb.core::mbc-write cart #x2100 3)
    (is (= 3 (lispgb.core::mbc-read cart #x4000)))
    (lispgb.core::mbc-write cart #x2000 #x0a)
    (lispgb.core::mbc-write cart #xa000 #xab)
    (is (= #xfb (lispgb.core::mbc-read cart #xa200)))
    (lispgb.core::mbc-write cart 0 0)
    (is (= #xff (lispgb.core::mbc-read cart #xa000)))))
(deftest mbc3-rtc ()
  (let ((cart (lispgb.core::make-cartridge (banked-rom #x10 2 3))))
    (lispgb.core::mbc-write cart #x2000 3)
    (is (= 3 (lispgb.core::mbc-read cart #x4000)))
    (lispgb.core::mbc-write cart 0 #x0a)
    (lispgb.core::mbc-write cart #x4000 8)
    (lispgb.core::mbc-sync-wall-clock cart 100)
    (lispgb.core::mbc-sync-wall-clock cart 159)
    (is (= 0 (lispgb.core::mbc-read cart #xa000)))
    (lispgb.core::mbc-write cart #x6000 0)
    (lispgb.core::mbc-write cart #x6000 1)
    (is (= 59 (lispgb.core::mbc-read cart #xa000)))
    (lispgb.core::mbc-sync-wall-clock cart 161)
    (is (= 59 (lispgb.core::mbc-read cart #xa000)))
    (lispgb.core::mbc-write cart #x6000 0)
    (lispgb.core::mbc-write cart #x6000 1)
    (is (= 1 (lispgb.core::mbc-read cart #xa000)))
    (lispgb.core::mbc-write cart #x4000 9)
    (is (= 1 (lispgb.core::mbc-read cart #xa000)))))
(deftest mbc5-nine-bit-bank ()
  (let ((cart (lispgb.core::make-cartridge (banked-rom #x1b 8 2))))
    (lispgb.core::mbc-write cart #x2000 0)
    (lispgb.core::mbc-write cart #x3000 1)
    (is (= 0 (lispgb.core::mbc-read cart #x4000)))
    (is (= 1 (lispgb.core::mbc-read cart #x4001)))
    (lispgb.core::mbc-write cart #x3000 0)
    (is (= 0 (lispgb.core::mbc-read cart #x4001)))))
(dolist (name '(mbc1-banks mbc2-nibbles mbc3-rtc mbc5-nine-bit-bank)) (register-pending name "T028"))
