;;; 最適化前の1画素ずつの描画を、比較用の参照実装として固定する。
(in-package #:lispgb.core)
(defun reference-ppu-render-line (ppu vram oam)
  (let* ((ly (ppu-ly ppu)) (lcdc (ppu-lcdc ppu)) (start (* ly 160))
         (cgb (ppu-cgb ppu)) (bg-enabled (or (ppu-cgb ppu) (logbitp 0 lcdc)))
         (frame (ppu-framebuffer ppu)) (colors (ppu-bg-colors ppu))
         (window (and bg-enabled (logbitp 5 lcdc) (>= ly (ppu-wy ppu)) (< (ppu-wx ppu) 167))))
    (dotimes (x 160)
      (let ((color 0) (attribute 0))
        (when bg-enabled
          (let* ((win (and window (>= x (- (ppu-wx ppu) 7))))
                 (sx (if win (- x (- (ppu-wx ppu) 7)) (wrap8 (+ x (ppu-scx ppu)))))
                 (sy (if win (ppu-window-line ppu) (wrap8 (+ ly (ppu-scy ppu)))))
                 (map (+ (if (logbitp (if win 6 3) lcdc) #x1c00 #x1800) (* 32 (ash sy -3)) (ash sx -3)))
                 (tile (aref vram map))
                 (attr (if cgb (aref vram (+ #x2000 map)) 0))
                 (row (logand sy 7)) (col (logand sx 7))
                 (address (+ (if (logbitp 4 lcdc) (* tile 16) (+ #x1000 (* (if (< tile 128) tile (- tile 256)) 16)))
                             (* 2 (if (logbitp 6 attr) (- 7 row) row))
                             (if (logbitp 3 attr) #x2000 0))))
            (setf attribute attr color (tile-pixel vram address (if (logbitp 5 attr) (- 7 col) col)))))
        (setf (aref colors x) color
              (aref (ppu-bg-priority ppu) x) (if (logbitp 7 attribute) 1 0)
              (aref frame (+ start x))
              (cond (cgb (cgb-color (ppu-bg-palette ppu) (+ (* 4 (logand 7 attribute)) color)))
                    (bg-enabled (dmg-color (ppu-bgp ppu) color)) (t #xffffffff)))))
    (when window (incf (ppu-window-line ppu)))
    (when (logbitp 1 lcdc)
      (fill (ppu-sprite-owned ppu) 0)
      (let* ((height (if (logbitp 2 lcdc) 16 8))
             (sprites (loop for i from 0 below 160 by 4
                            when (<= 0 (- (+ ly 16) (aref oam i)) (1- height)) collect i into found
                            and count t into count when (= count 10) return found finally (return found))))
        (when (or (not cgb) (= (ppu-opri ppu) 1))
          (setf sprites (stable-sort sprites #'< :key (lambda (i) (aref oam (1+ i))))))
        (dolist (i sprites)
          (let* ((left (- (aref oam (+ i 1)) 8)) (attr (aref oam (+ i 3)))
                 (row (- (+ ly 16) (aref oam i)))
                 (y (if (logbitp 6 attr) (- height 1 row) row))
                 (tile (logand (aref oam (+ i 2)) (if (= height 16) #xfe #xff)))
                 (address (+ (* tile 16) (* 2 y) (if (and cgb (logbitp 3 attr)) #x2000 0))))
            (dotimes (col 8)
              (let ((x (+ left col)))
                (when (and (<= 0 x 159) (zerop (aref (ppu-sprite-owned ppu) x)))
                  (let ((color (tile-pixel vram address (if (logbitp 5 attr) (- 7 col) col))))
                    (unless (zerop color)
                      (setf (aref (ppu-sprite-owned ppu) x) 1)
                      (unless (and (plusp (aref colors x))
                                   (if cgb (and (logbitp 0 lcdc) (or (logbitp 7 attr) (= 1 (aref (ppu-bg-priority ppu) x))))
                                       (logbitp 7 attr)))
                        (setf (aref frame (+ start x))
                              (if cgb (cgb-color (ppu-obj-palette ppu) (+ (* 4 (logand 7 attr)) color))
                                  (dmg-color (if (logbitp 4 attr) (ppu-obp1 ppu) (ppu-obp0 ppu)) color)))))))))))))))

