(in-package #:lispgb.tests)
(deftest ppu-mode-timing ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff40 #x91)
    (is (= 2 (logand 3 (lispgb.core::bus-read bus #xff41))))
    (lispgb.core::bus-tick bus 80)
    (is (= 3 (logand 3 (lispgb.core::bus-read bus #xff41))))
    (lispgb.core::bus-tick bus 172)
    (is (= 0 (logand 3 (lispgb.core::bus-read bus #xff41))))
    (lispgb.core::bus-tick bus (- (* 144 456) 252))
    (is (= 144 (lispgb.core::bus-read bus #xff44)))
    (is (= 1 (logand 3 (lispgb.core::bus-read bus #xff41))))
    (is (logbitp 0 (lispgb.core::bus-if bus)))
    (lispgb.core::bus-write bus #xff40 0)
    (is (= 0 (lispgb.core::bus-read bus #xff44)))))
(deftest ppu-stat-edge ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff40 #x80)
    (lispgb.core::bus-write bus #xff45 1)
    (lispgb.core::bus-write bus #xff41 #x40)
    (lispgb.core::bus-tick bus 456)
    (is (logbitp 1 (lispgb.core::bus-if bus)))
    (setf (lispgb.core::bus-if bus) 0)
    (lispgb.core::bus-tick bus 4)
    (is (= 0 (lispgb.core::bus-if bus)))))
(deftest ppu-tile-decode ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #x8000 #x80)
    (lispgb.core::bus-write bus #x8001 #x40)
    (lispgb.core::bus-write bus #xff47 #xe4)
    (lispgb.core::bus-write bus #xff40 #x91)
    (lispgb.core::bus-tick bus 252)
    (let ((pixels (lispgb.core::ppu-framebuffer (lispgb.core::bus-ppu bus))))
      (is (= #xffaaaaaa (aref pixels 0)))
      (is (= #xff555555 (aref pixels 1)))
      (is (= #xffffffff (aref pixels 2))))))
