(in-package #:lispgb.tests)
(deftest ppu-mode-timing ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff40 #x91)
    (is (= 2 (logand 3 (lispgb.core::bus-read bus #xff41))))
    (lispgb.core::bus-tick bus 80)
    (is (= 3 (logand 3 (lispgb.core::bus-read bus #xff41))))
    (lispgb.core::bus-tick bus 172)
    (is (= 0 (logand 3 (lispgb.core::bus-read bus #xff41))))
    (lispgb.core::bus-tick bus (- (* 144 456) 252))
    (is (= 144 (lispgb.core::bus-read bus #xff44)))
    (is (= 1 (logand 3 (lispgb.core::bus-read bus #xff41))))
    (is (logbitp 0 (lispgb.core::bus-if bus)))
    (lispgb.core::bus-write bus #xff40 0)
    (is (= 0 (lispgb.core::bus-read bus #xff44)))))
(deftest ppu-stat-edge ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff40 #x80)
    (lispgb.core::bus-write bus #xff45 1)
    (lispgb.core::bus-write bus #xff41 #x40)
    (lispgb.core::bus-tick bus 456)
    (is (logbitp 1 (lispgb.core::bus-if bus)))
    (setf (lispgb.core::bus-if bus) 0)
    (lispgb.core::bus-tick bus 4)
    (is (= 0 (lispgb.core::bus-if bus)))))
(deftest ppu-tile-decode ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #x8000 #x80)
    (lispgb.core::bus-write bus #x8001 #x40)
    (lispgb.core::bus-write bus #xff47 #xe4)
    (lispgb.core::bus-write bus #xff40 #x91)
    (lispgb.core::bus-tick bus 252)
    (let ((pixels (lispgb.core::ppu-framebuffer (lispgb.core::bus-ppu bus))))
      (is (= #xffaaaaaa (aref pixels 0)))
      (is (= #xff555555 (aref pixels 1)))
      (is (= #xffffffff (aref pixels 2))))))

(deftest ppu-render-reference-equivalence ()
  ;; 固定シードで属性・スクロール・窓の部分タイル・重なるスプライトを組み合わせる。
  (let ((seed 12345))
    (flet ((next-byte () (setf seed (logand #xffffffff (+ (* seed 1664525) 1013904223)))
                       (ldb (byte 8 16) seed)))
      (dotimes (case-index 128)
        (let* ((cgb (oddp case-index))
               (ppu (lispgb.core::make-ppu :cgb cgb))
               (reference (lispgb.core::make-ppu :cgb cgb))
               (vram (make-array 16384 :element-type '(unsigned-byte 8)))
               (oam (make-array 160 :element-type '(unsigned-byte 8)))
               (ly (mod (* case-index 13) 144)))
          (dotimes (i (length vram)) (setf (aref vram i) (next-byte)))
          (dotimes (i 40)
            (setf (aref oam (* i 4)) (if (< i 16) (+ ly 16) (next-byte))
                  (aref oam (+ (* i 4) 1)) (mod (* i 11) 176)
                  (aref oam (+ (* i 4) 2)) (next-byte)
                  (aref oam (+ (* i 4) 3)) (next-byte)))
          (let ((lcdc (+ #x80 (mod (* case-index 29) 128)))
                (scx (next-byte)) (scy (next-byte))
                (wx (nth (mod case-index 9) '(0 1 6 7 8 15 159 166 167)))
                (wy (if (zerop (mod case-index 3)) (1+ ly) 0))
                (bgp (next-byte)) (obp0 (next-byte)) (obp1 (next-byte)))
            (dolist (p (list ppu reference))
              (setf (lispgb.core::ppu-ly p) ly (lispgb.core::ppu-window-line p) (mod case-index 144))
              (loop for address in '(#xff40 #xff42 #xff43 #xff4a #xff4b #xff47 #xff48 #xff49 #xff6c)
                    for value in (list lcdc scy scx wy wx bgp obp0 obp1 (mod case-index 2))
                    do (lispgb.core::ppu-write p address value))
              ;; LCD有効化でLYが戻るため、対象ラインは最後に設定する。
              (setf (lispgb.core::ppu-ly p) ly (lispgb.core::ppu-window-line p) (mod case-index 144))))
          (dotimes (i 64)
            (let ((bg (next-byte)) (obj (next-byte)))
              (dolist (p (list ppu reference))
                (lispgb.core::ppu-write p #xff68 i) (lispgb.core::ppu-write p #xff69 bg)
                (lispgb.core::ppu-write p #xff6a i) (lispgb.core::ppu-write p #xff6b obj))))
          (lispgb.core::reference-ppu-render-line reference vram oam)
          (lispgb.core::ppu-render-line ppu vram oam)
          (is (equalp (lispgb.core::ppu-framebuffer reference) (lispgb.core::ppu-framebuffer ppu))
              (format nil "描画ケース ~D" case-index))
          (is (= (lispgb.core::ppu-window-line reference) (lispgb.core::ppu-window-line ppu))))))))

(deftest ppu-palette-cache-write-and-restore ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom :cgb #x80)))
         (ppu (lispgb.core::bus-ppu (lispgb.core::machine-bus machine))))
    (lispgb.core::ppu-write ppu #xff68 #x80)
    (lispgb.core::ppu-write ppu #xff69 #x1f)
    (lispgb.core::ppu-write ppu #xff69 0)
    (is (= #xffff0000 (aref (lispgb.core::ppu-bg-argb ppu) 0)))
    (let ((saved (lispgb.core:save-state machine)))
      (lispgb.core::ppu-write ppu #xff68 0)
      (setf (lispgb.core::ppu-mode ppu) 3)
      (lispgb.core::ppu-write ppu #xff69 0)
      (is (= #xffff0000 (aref (lispgb.core::ppu-bg-argb ppu) 0)))
      (lispgb.core:load-state machine saved)
      (let ((restored (lispgb.core::bus-ppu (lispgb.core::machine-bus machine))))
        (is (= #xffff0000 (aref (lispgb.core::ppu-bg-argb restored) 0)))
        (is (equalp saved (lispgb.core:save-state machine)))))))
