(in-package #:lispgb.tests)
(deftest savestate-roundtrip ()
  (let* ((rom (synthetic-rom :cgb #x80 :type #x10 :ram-code 3))
         (machine (lispgb.core:make-machine rom)))
    ;; 安定してループする ROM で100回、継続実行も含めて比べる。
    (setf (aref rom #x100) #x18 (aref rom #x101) #xfe)
    (dotimes (i 100)
      (lispgb.core:run-frame machine)
      (let ((state (lispgb.core::save-state machine))
            (registers (lispgb.core:machine-cpu-registers machine))
            (pixels (copy-seq (lispgb.core:machine-framebuffer machine))))
        (is (= (length state) (lispgb.core::savestate-size machine)))
        (lispgb.core:run-frame machine)
        (let ((future (lispgb.core::save-state machine)))
          (lispgb.core::load-state machine state)
          (is (equal registers (lispgb.core:machine-cpu-registers machine)))
          (is (equalp pixels (lispgb.core:machine-framebuffer machine)))
          (is (equalp state (lispgb.core::save-state machine)))
          (lispgb.core:run-frame machine)
          (is (equalp future (lispgb.core::save-state machine))))))))
(deftest savestate-rejection-atomic ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom)))
         (state (lispgb.core::save-state machine)))
    (dolist (offset '(0 4 8))
      (let ((bad (copy-seq state)))
        (incf (aref bad offset))
        (is (signals-condition-p 'lispgb.core::savestate-error (lambda () (lispgb.core::load-state machine bad))))
        (is (equalp state (lispgb.core::save-state machine)))))
    (dolist (size (list 0 4 8 9 (1- (length state))))
      (is (signals-condition-p 'lispgb.core::savestate-error
                              (lambda () (lispgb.core::load-state machine (subseq state 0 size)))))
      (is (equalp state (lispgb.core::save-state machine))))))
(deftest savestate-clears-audio ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom)))
         (state (lispgb.core::save-state machine))
         (apu (lispgb.core::bus-apu (lispgb.core::machine-bus machine))))
    (fill (lispgb.core::apu-ring apu) 1234)
    (setf (lispgb.core::apu-ring-count apu) 8192)
    (lispgb.core::load-state machine state)
    (let ((restored (lispgb.core::bus-apu (lispgb.core::machine-bus machine))))
      (is (every #'zerop (lispgb.core::apu-ring restored)))
      (is (= 0 (lispgb.core::apu-ring-count restored))))))
(deftest savestate-invalid-body ()
  (let* ((machine (lispgb.core:make-machine (synthetic-rom)))
         (before (lispgb.core::save-state machine)) (bad (copy-seq before)))
    ;; CPU の IME は0/1だけを許可する。
    (setf (aref bad 22) 2)
    (is (signals-condition-p 'lispgb.core::savestate-error (lambda () (lispgb.core::load-state machine bad))))
    (is (equalp before (lispgb.core::save-state machine)))))
(let ((path (asdf:system-relative-pathname "lispgb/tests" "tests/roms/blargg/dmg_sound/rom_singles/01-registers.gb")))
  (when (probe-file path)
    (deftest savestate-active-rom ()
      (let* ((machine (run-rom path :max-frames 30)) (state (lispgb.core::save-state machine)))
        (lispgb.core:run-frame machine)
        (let ((future (lispgb.core::save-state machine)))
          (lispgb.core::load-state machine state)
          (lispgb.core:run-frame machine)
          (is (equalp future (lispgb.core::save-state machine))))))))
