(in-package #:lispgb.tests)

(deftest timer-divider-and-frequency ()
  (loop for code below 4 for period in '(1024 16 64 256)
        do (let ((bus (lispgb.core::make-bus)))
             (lispgb.core::bus-write bus #xff07 (+ 4 code))
             (lispgb.core::bus-tick bus (1- period))
             (is (zerop (lispgb.core::bus-read bus #xff05)))
             (lispgb.core::bus-tick bus 1)
             (is (= 1 (lispgb.core::bus-read bus #xff05)))))
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-tick bus 512)
    (is (= 2 (lispgb.core::bus-read bus #xff04)))
    (lispgb.core::bus-write bus #xff04 #xff)
    (is (zerop (lispgb.core::bus-read bus #xff04)))))

(deftest timer-falling-edge ()
  (dolist (address '(#xff04 #xff07))
    (let ((bus (lispgb.core::make-bus)))
      (lispgb.core::bus-write bus #xff07 5)
      (lispgb.core::bus-tick bus 8)
      (lispgb.core::bus-write bus address 0)
      (is (= 1 (lispgb.core::bus-read bus #xff05))))))

(deftest timer-overflow ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff07 5)
    (lispgb.core::bus-write bus #xff05 #xff)
    (lispgb.core::bus-write bus #xff06 #x42)
    (lispgb.core::bus-tick bus 16)
    (is (= 0 (lispgb.core::bus-read bus #xff05)))
    (lispgb.core::bus-tick bus 3)
    (is (= 0 (lispgb.core::bus-if bus)))
    (lispgb.core::bus-tick bus 1)
    (is (= #x42 (lispgb.core::bus-read bus #xff05)))
    (is (= 4 (lispgb.core::bus-if bus)))
    (lispgb.core::bus-write bus #xff05 #x55)
    (is (= #x42 (lispgb.core::bus-read bus #xff05)))
    (lispgb.core::bus-write bus #xff06 #x66)
    (is (= #x66 (lispgb.core::bus-read bus #xff05)))))

(deftest timer-cancel-reload ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff07 5)
    (lispgb.core::bus-write bus #xff05 #xff)
    (lispgb.core::bus-tick bus 16)
    (is (= 0 (lispgb.core::bus-read bus #xff05)))
    (lispgb.core::bus-write bus #xff05 3)
    (lispgb.core::bus-tick bus 4)
    (is (= 3 (lispgb.core::bus-read bus #xff05)))
    (is (= 0 (lispgb.core::bus-if bus)))))

(deftest timer-batch-reference-equivalence ()
  (let ((seed 56789))
    (flet ((next-value () (setf seed (logand #xffffffff (+ (* seed 1664525) 1013904223)))))
      (dotimes (code 8)
        (let ((timer (lispgb.core::make-timer :div-counter #xfff9 :tima #xfe :tma #xfd :tac code))
              (reference (lispgb.core::make-timer :div-counter #xfff9 :tima #xfe :tma #xfd :tac code)))
          (dotimes (i 512)
            (let ((choice (ldb (byte 3 16) (next-value))))
              (if (< choice 4)
                  (let ((address (+ #xff04 choice)) (value (ldb (byte 8 16) (next-value))))
                    (lispgb.core::timer-write timer address value)
                    (lispgb.core::timer-write reference address value))
                  (let ((cycles (nth (mod (ldb (byte 8 16) (next-value)) 15)
                                     '(0 1 2 3 4 7 8 15 16 31 64 255 256 1024 65536))))
                    (is (eq (lispgb.core::timer-tick timer cycles)
                            (lispgb.core::reference-timer-tick reference cycles)))))
              (is (equalp timer reference) (format nil "TAC ~D / 操作 ~D" code i)))))))))
