(in-package #:lispgb.tests)

(deftest timer-divider-and-frequency ()
  (loop for code below 4 for period in '(1024 16 64 256)
        do (let ((bus (lispgb.core::make-bus)))
             (lispgb.core::bus-write bus #xff07 (+ 4 code))
             (lispgb.core::bus-tick bus (1- period))
             (is (zerop (lispgb.core::bus-read bus #xff05)))
             (lispgb.core::bus-tick bus 1)
             (is (= 1 (lispgb.core::bus-read bus #xff05)))))
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-tick bus 512)
    (is (= 2 (lispgb.core::bus-read bus #xff04)))
    (lispgb.core::bus-write bus #xff04 #xff)
    (is (zerop (lispgb.core::bus-read bus #xff04)))))

(deftest timer-falling-edge ()
  (dolist (address '(#xff04 #xff07))
    (let ((bus (lispgb.core::make-bus)))
      (lispgb.core::bus-write bus #xff07 5)
      (lispgb.core::bus-tick bus 8)
      (lispgb.core::bus-write bus address 0)
      (is (= 1 (lispgb.core::bus-read bus #xff05))))))

(deftest timer-overflow ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff07 5)
    (lispgb.core::bus-write bus #xff05 #xff)
    (lispgb.core::bus-write bus #xff06 #x42)
    (lispgb.core::bus-tick bus 16)
    (is (= 0 (lispgb.core::bus-read bus #xff05)))
    (lispgb.core::bus-tick bus 3)
    (is (= 0 (lispgb.core::bus-if bus)))
    (lispgb.core::bus-tick bus 1)
    (is (= #x42 (lispgb.core::bus-read bus #xff05)))
    (is (= 4 (lispgb.core::bus-if bus)))
    (lispgb.core::bus-write bus #xff05 #x55)
    (is (= #x42 (lispgb.core::bus-read bus #xff05)))
    (lispgb.core::bus-write bus #xff06 #x66)
    (is (= #x66 (lispgb.core::bus-read bus #xff05)))))

(deftest timer-cancel-reload ()
  (let ((bus (lispgb.core::make-bus)))
    (lispgb.core::bus-write bus #xff07 5)
    (lispgb.core::bus-write bus #xff05 #xff)
    (lispgb.core::bus-tick bus 16)
    (is (= 0 (lispgb.core::bus-read bus #xff05)))
    (lispgb.core::bus-write bus #xff05 3)
    (lispgb.core::bus-tick bus 4)
    (is (= 3 (lispgb.core::bus-read bus #xff05)))
    (is (= 0 (lispgb.core::bus-if bus)))))
(dolist (name '(timer-divider-and-frequency timer-falling-edge timer-overflow timer-cancel-reload))
  (register-pending name "T021"))
